# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/chearttdload.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TDDialog(object):
    def setupUi(self, TDDialog):
        TDDialog.setObjectName(_fromUtf8("TDDialog"))
        TDDialog.resize(785, 816)
        TDDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(TDDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.gridGroupBox = QtGui.QGroupBox(TDDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gridGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.gridGroupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tfile = QtGui.QLineEdit(self.gridGroupBox)
        self.tfile.setObjectName(_fromUtf8("tfile"))
        self.horizontalLayout_2.addWidget(self.tfile)
        self.tchoose = QtGui.QPushButton(self.gridGroupBox)
        self.tchoose.setObjectName(_fromUtf8("tchoose"))
        self.horizontalLayout_2.addWidget(self.tchoose)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(self.gridGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.geomBox = QtGui.QComboBox(self.gridGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geomBox.sizePolicy().hasHeightForWidth())
        self.geomBox.setSizePolicy(sizePolicy)
        self.geomBox.setObjectName(_fromUtf8("geomBox"))
        self.horizontalLayout_5.addWidget(self.geomBox)
        self.label_3 = QtGui.QLabel(self.gridGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.basisBox = QtGui.QComboBox(self.gridGroupBox)
        self.basisBox.setObjectName(_fromUtf8("basisBox"))
        self.horizontalLayout_5.addWidget(self.basisBox)
        self.label_4 = QtGui.QLabel(self.gridGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.orderBox = QtGui.QSpinBox(self.gridGroupBox)
        self.orderBox.setMinimum(1)
        self.orderBox.setMaximum(20)
        self.orderBox.setObjectName(_fromUtf8("orderBox"))
        self.horizontalLayout_5.addWidget(self.orderBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addWidget(self.gridGroupBox)
        self.groupBox_2 = QtGui.QGroupBox(TDDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.startTimeBox = QtGui.QSpinBox(self.groupBox_2)
        self.startTimeBox.setMaximum(99999)
        self.startTimeBox.setObjectName(_fromUtf8("startTimeBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.startTimeBox)
        self.intervalBox = QtGui.QSpinBox(self.groupBox_2)
        self.intervalBox.setMinimum(1)
        self.intervalBox.setMaximum(99999)
        self.intervalBox.setObjectName(_fromUtf8("intervalBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.intervalBox)
        self.horizontalLayout_10.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.groupBox = QtGui.QGroupBox(TDDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setTextFormat(QtCore.Qt.AutoText)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.absoluteRadio = QtGui.QRadioButton(self.groupBox)
        self.absoluteRadio.setChecked(True)
        self.absoluteRadio.setObjectName(_fromUtf8("absoluteRadio"))
        self.horizontalLayout_4.addWidget(self.absoluteRadio)
        self.displaceRadio = QtGui.QRadioButton(self.groupBox)
        self.displaceRadio.setObjectName(_fromUtf8("displaceRadio"))
        self.horizontalLayout_4.addWidget(self.displaceRadio)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.xfile = QtGui.QLineEdit(self.groupBox)
        self.xfile.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xfile.sizePolicy().hasHeightForWidth())
        self.xfile.setSizePolicy(sizePolicy)
        self.xfile.setMinimumSize(QtCore.QSize(0, 0))
        self.xfile.setObjectName(_fromUtf8("xfile"))
        self.horizontalLayout_3.addWidget(self.xfile)
        self.xchoose = QtGui.QPushButton(self.groupBox)
        self.xchoose.setEnabled(False)
        self.xchoose.setMaximumSize(QtCore.QSize(100, 16777215))
        self.xchoose.setObjectName(_fromUtf8("xchoose"))
        self.horizontalLayout_3.addWidget(self.xchoose)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.addNodesButton = QtGui.QPushButton(self.groupBox)
        self.addNodesButton.setObjectName(_fromUtf8("addNodesButton"))
        self.horizontalLayout.addWidget(self.addNodesButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.xfileTable = QtGui.QTableWidget(self.groupBox)
        self.xfileTable.setDragEnabled(True)
        self.xfileTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.xfileTable.setObjectName(_fromUtf8("xfileTable"))
        self.xfileTable.setColumnCount(2)
        self.xfileTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.xfileTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.xfileTable.setHorizontalHeaderItem(1, item)
        self.xfileTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.xfileTable)
        self.xfileTable.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        self.gridGroupBox_2 = QtGui.QGroupBox(TDDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox_2.sizePolicy().hasHeightForWidth())
        self.gridGroupBox_2.setSizePolicy(sizePolicy)
        self.gridGroupBox_2.setObjectName(_fromUtf8("gridGroupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gridGroupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_15 = QtGui.QLabel(self.gridGroupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_4.addWidget(self.label_15)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.ftfile = QtGui.QLineEdit(self.gridGroupBox_2)
        self.ftfile.setObjectName(_fromUtf8("ftfile"))
        self.horizontalLayout_6.addWidget(self.ftfile)
        self.ftchoose = QtGui.QPushButton(self.gridGroupBox_2)
        self.ftchoose.setObjectName(_fromUtf8("ftchoose"))
        self.horizontalLayout_6.addWidget(self.ftchoose)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_9 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.fgeomBox = QtGui.QComboBox(self.gridGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgeomBox.sizePolicy().hasHeightForWidth())
        self.fgeomBox.setSizePolicy(sizePolicy)
        self.fgeomBox.setObjectName(_fromUtf8("fgeomBox"))
        self.horizontalLayout_7.addWidget(self.fgeomBox)
        self.label_10 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.fbasisBox = QtGui.QComboBox(self.gridGroupBox_2)
        self.fbasisBox.setObjectName(_fromUtf8("fbasisBox"))
        self.horizontalLayout_7.addWidget(self.fbasisBox)
        self.label_11 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.forderBox = QtGui.QSpinBox(self.gridGroupBox_2)
        self.forderBox.setMinimum(1)
        self.forderBox.setMaximum(20)
        self.forderBox.setObjectName(_fromUtf8("forderBox"))
        self.horizontalLayout_7.addWidget(self.forderBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_12 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.addFieldsButton = QtGui.QPushButton(self.gridGroupBox_2)
        self.addFieldsButton.setObjectName(_fromUtf8("addFieldsButton"))
        self.horizontalLayout_8.addWidget(self.addFieldsButton)
        self.label_16 = QtGui.QLabel(self.gridGroupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        self.dimBox = QtGui.QSpinBox(self.gridGroupBox_2)
        self.dimBox.setMinimum(1)
        self.dimBox.setProperty("value", 1)
        self.dimBox.setObjectName(_fromUtf8("dimBox"))
        self.horizontalLayout_8.addWidget(self.dimBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.dfileTable = QtGui.QTableWidget(self.gridGroupBox_2)
        self.dfileTable.setDragEnabled(True)
        self.dfileTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.dfileTable.setObjectName(_fromUtf8("dfileTable"))
        self.dfileTable.setColumnCount(2)
        self.dfileTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.dfileTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dfileTable.setHorizontalHeaderItem(1, item)
        self.dfileTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.dfileTable)
        self.verticalLayout.addWidget(self.gridGroupBox_2)
        self.buttonBox = QtGui.QDialogButtonBox(TDDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TDDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TDDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TDDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TDDialog)

    def retranslateUi(self, TDDialog):
        TDDialog.setWindowTitle(_translate("TDDialog", "Choose Cheart Input Files", None))
        self.gridGroupBox.setTitle(_translate("TDDialog", "Topology", None))
        self.label_2.setText(_translate("TDDialog", "Topology File (*.T):", None))
        self.tchoose.setText(_translate("TDDialog", "C&hoose...", None))
        self.label_5.setText(_translate("TDDialog", "Geometry:", None))
        self.label_3.setText(_translate("TDDialog", "Basis Function:", None))
        self.label_4.setText(_translate("TDDialog", "Order:", None))
        self.groupBox_2.setTitle(_translate("TDDialog", "Timing", None))
        self.label_17.setText(_translate("TDDialog", "Start Time:", None))
        self.label_18.setText(_translate("TDDialog", "Interval:", None))
        self.groupBox.setTitle(_translate("TDDialog", "Geometry Keyframes", None))
        self.label_13.setText(_translate("TDDialog", "Choose geometry files to define keyframes, which all use the above topology. If each frame is a set of node", None))
        self.label_14.setText(_translate("TDDialog", "displacement values, an initial node file must be provided.", None))
        self.label_6.setText(_translate("TDDialog", "Keyframe Type:", None))
        self.absoluteRadio.setText(_translate("TDDialog", "Absolute Positions", None))
        self.displaceRadio.setText(_translate("TDDialog", "Displacement Values", None))
        self.label.setText(_translate("TDDialog", "Initial Node File (Displacement only) (*.X):", None))
        self.xchoose.setText(_translate("TDDialog", "&Choose...", None))
        self.label_7.setText(_translate("TDDialog", "Keyframe Node Files (*.X,*.D):", None))
        self.addNodesButton.setText(_translate("TDDialog", "Add Node Files...", None))
        item = self.xfileTable.horizontalHeaderItem(0)
        item.setText(_translate("TDDialog", "#", None))
        item = self.xfileTable.horizontalHeaderItem(1)
        item.setText(_translate("TDDialog", "Filenames", None))
        self.gridGroupBox_2.setTitle(_translate("TDDialog", "Data Field Keyframes", None))
        self.label_15.setText(_translate("TDDialog", "Choose field files to define keyframes, which may use the given topology or the spatial topology defined above.", None))
        self.label_8.setText(_translate("TDDialog", "Topology File (*.T):", None))
        self.ftchoose.setText(_translate("TDDialog", "C&hoose...", None))
        self.label_9.setText(_translate("TDDialog", "Geometry:", None))
        self.label_10.setText(_translate("TDDialog", "Basis Function:", None))
        self.label_11.setText(_translate("TDDialog", "Order:", None))
        self.label_12.setText(_translate("TDDialog", "Keyframe Field Files (*.D):", None))
        self.addFieldsButton.setText(_translate("TDDialog", "Add Field Files...", None))
        self.label_16.setText(_translate("TDDialog", "Data Dimension:", None))
        item = self.dfileTable.horizontalHeaderItem(0)
        item.setText(_translate("TDDialog", "#", None))
        item = self.dfileTable.horizontalHeaderItem(1)
        item.setText(_translate("TDDialog", "Filenames", None))

