# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/CTMotionProp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CTMotionProp(object):
    def setupUi(self, CTMotionProp):
        CTMotionProp.setObjectName(_fromUtf8("CTMotionProp"))
        CTMotionProp.resize(358, 512)
        self.verticalLayout = QtGui.QVBoxLayout(CTMotionProp)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(CTMotionProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ctDicomButton = QtGui.QPushButton(self.groupBox)
        self.ctDicomButton.setObjectName(_fromUtf8("ctDicomButton"))
        self.verticalLayout_2.addWidget(self.ctDicomButton)
        self.niftiButton = QtGui.QPushButton(self.groupBox)
        self.niftiButton.setObjectName(_fromUtf8("niftiButton"))
        self.verticalLayout_2.addWidget(self.niftiButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.trackImgBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackImgBox.sizePolicy().hasHeightForWidth())
        self.trackImgBox.setSizePolicy(sizePolicy)
        self.trackImgBox.setObjectName(_fromUtf8("trackImgBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.trackImgBox)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.trackMaskBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackMaskBox.sizePolicy().hasHeightForWidth())
        self.trackMaskBox.setSizePolicy(sizePolicy)
        self.trackMaskBox.setObjectName(_fromUtf8("trackMaskBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.trackMaskBox)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.paramEdit = QtGui.QLineEdit(self.groupBox_2)
        self.paramEdit.setObjectName(_fromUtf8("paramEdit"))
        self.horizontalLayout_2.addWidget(self.paramEdit)
        self.chooseParamButton = QtGui.QPushButton(self.groupBox_2)
        self.chooseParamButton.setObjectName(_fromUtf8("chooseParamButton"))
        self.horizontalLayout_2.addWidget(self.chooseParamButton)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.trackButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackButton.sizePolicy().hasHeightForWidth())
        self.trackButton.setSizePolicy(sizePolicy)
        self.trackButton.setObjectName(_fromUtf8("trackButton"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.trackButton)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.trackName = QtGui.QLineEdit(self.groupBox_2)
        self.trackName.setObjectName(_fromUtf8("trackName"))
        self.horizontalLayout_14.addWidget(self.trackName)
        self.label_68 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_14.addWidget(self.label_68)
        self.formLayout_3.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.label_67 = QtGui.QLabel(self.groupBox_2)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_67)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.trackObjBox = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackObjBox.sizePolicy().hasHeightForWidth())
        self.trackObjBox.setSizePolicy(sizePolicy)
        self.trackObjBox.setObjectName(_fromUtf8("trackObjBox"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.trackObjBox)
        self.applyTrackButton = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyTrackButton.sizePolicy().hasHeightForWidth())
        self.applyTrackButton.setSizePolicy(sizePolicy)
        self.applyTrackButton.setObjectName(_fromUtf8("applyTrackButton"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.applyTrackButton)
        self.trackDataBox = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackDataBox.sizePolicy().hasHeightForWidth())
        self.trackDataBox.setSizePolicy(sizePolicy)
        self.trackDataBox.setObjectName(_fromUtf8("trackDataBox"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.trackDataBox)
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.verticalLayout.addWidget(self.groupBox_6)

        self.retranslateUi(CTMotionProp)
        QtCore.QMetaObject.connectSlotsByName(CTMotionProp)

    def retranslateUi(self, CTMotionProp):
        CTMotionProp.setWindowTitle(_translate("CTMotionProp", "Form", None))
        self.groupBox.setTitle(_translate("CTMotionProp", "Import Data", None))
        self.ctDicomButton.setText(_translate("CTMotionProp", "CT DICOM Series", None))
        self.niftiButton.setText(_translate("CTMotionProp", "NIfTI Image Stack", None))
        self.groupBox_2.setTitle(_translate("CTMotionProp", "Motion Tracking", None))
        self.label_9.setText(_translate("CTMotionProp", "Image Series", None))
        self.label_10.setText(_translate("CTMotionProp", "Mask Image", None))
        self.label_11.setText(_translate("CTMotionProp", "Param File", None))
        self.chooseParamButton.setText(_translate("CTMotionProp", "Choose", None))
        self.trackButton.setText(_translate("CTMotionProp", "Start Motion Tracking", None))
        self.label_68.setText(_translate("CTMotionProp", "(blank for default)", None))
        self.label_67.setText(_translate("CTMotionProp", "Track Name", None))
        self.groupBox_6.setTitle(_translate("CTMotionProp", "Apply Tracking", None))
        self.label_12.setText(_translate("CTMotionProp", "Object", None))
        self.applyTrackButton.setText(_translate("CTMotionProp", "Apply Tracking", None))
        self.label_18.setText(_translate("CTMotionProp", "Track Data", None))

