# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/CTMotionProp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CTMotionProp(object):
    def setupUi(self, CTMotionProp):
        CTMotionProp.setObjectName(_fromUtf8("CTMotionProp"))
        CTMotionProp.resize(400, 1067)
        self.verticalLayout = QtGui.QVBoxLayout(CTMotionProp)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(CTMotionProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ctDicomButton = QtGui.QPushButton(self.groupBox)
        self.ctDicomButton.setObjectName(_fromUtf8("ctDicomButton"))
        self.verticalLayout_2.addWidget(self.ctDicomButton)
        self.niftiButton = QtGui.QPushButton(self.groupBox)
        self.niftiButton.setObjectName(_fromUtf8("niftiButton"))
        self.verticalLayout_2.addWidget(self.niftiButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_5 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.resampleImgBox = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resampleImgBox.sizePolicy().hasHeightForWidth())
        self.resampleImgBox.setSizePolicy(sizePolicy)
        self.resampleImgBox.setObjectName(_fromUtf8("resampleImgBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.resampleImgBox)
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.srcVoxelLabel = QtGui.QLabel(self.groupBox_5)
        self.srcVoxelLabel.setObjectName(_fromUtf8("srcVoxelLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.srcVoxelLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.isotropicBox = QtGui.QCheckBox(self.groupBox_5)
        self.isotropicBox.setChecked(True)
        self.isotropicBox.setObjectName(_fromUtf8("isotropicBox"))
        self.horizontalLayout.addWidget(self.isotropicBox)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.resampleButton = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resampleButton.sizePolicy().hasHeightForWidth())
        self.resampleButton.setSizePolicy(sizePolicy)
        self.resampleButton.setObjectName(_fromUtf8("resampleButton"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.resampleButton)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.voxXBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.voxXBox.setMinimum(0.01)
        self.voxXBox.setMaximum(20.0)
        self.voxXBox.setSingleStep(0.1)
        self.voxXBox.setProperty("value", 1.0)
        self.voxXBox.setObjectName(_fromUtf8("voxXBox"))
        self.horizontalLayout_3.addWidget(self.voxXBox)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.voxYBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.voxYBox.setMinimum(0.01)
        self.voxYBox.setMaximum(20.0)
        self.voxYBox.setSingleStep(0.1)
        self.voxYBox.setProperty("value", 1.0)
        self.voxYBox.setObjectName(_fromUtf8("voxYBox"))
        self.horizontalLayout_3.addWidget(self.voxYBox)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.voxZBox = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.voxZBox.setMinimum(0.01)
        self.voxZBox.setMaximum(20.0)
        self.voxZBox.setSingleStep(0.1)
        self.voxZBox.setProperty("value", 1.0)
        self.voxZBox.setObjectName(_fromUtf8("voxZBox"))
        self.horizontalLayout_3.addWidget(self.voxZBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_7 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.choose3ptImgBox = QtGui.QComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose3ptImgBox.sizePolicy().hasHeightForWidth())
        self.choose3ptImgBox.setSizePolicy(sizePolicy)
        self.choose3ptImgBox.setObjectName(_fromUtf8("choose3ptImgBox"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.choose3ptImgBox)
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.show3ptButton = QtGui.QPushButton(self.groupBox_7)
        self.show3ptButton.setObjectName(_fromUtf8("show3ptButton"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.show3ptButton)
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.resample3ptButton = QtGui.QPushButton(self.groupBox_7)
        self.resample3ptButton.setObjectName(_fromUtf8("resample3ptButton"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.resample3ptButton)
        self.createSegButton = QtGui.QPushButton(self.groupBox_7)
        self.createSegButton.setObjectName(_fromUtf8("createSegButton"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.createSegButton)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox_8)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.genMeshSegBox = QtGui.QComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genMeshSegBox.sizePolicy().hasHeightForWidth())
        self.genMeshSegBox.setSizePolicy(sizePolicy)
        self.genMeshSegBox.setObjectName(_fromUtf8("genMeshSegBox"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.genMeshSegBox)
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.genMeshRefineBox = QtGui.QSpinBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genMeshRefineBox.sizePolicy().hasHeightForWidth())
        self.genMeshRefineBox.setSizePolicy(sizePolicy)
        self.genMeshRefineBox.setMaximum(7)
        self.genMeshRefineBox.setProperty("value", 1)
        self.genMeshRefineBox.setObjectName(_fromUtf8("genMeshRefineBox"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.genMeshRefineBox)
        self.genMeshSegButton = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genMeshSegButton.sizePolicy().hasHeightForWidth())
        self.genMeshSegButton.setSizePolicy(sizePolicy)
        self.genMeshSegButton.setObjectName(_fromUtf8("genMeshSegButton"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.genMeshSegButton)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_2 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.trackImgBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackImgBox.sizePolicy().hasHeightForWidth())
        self.trackImgBox.setSizePolicy(sizePolicy)
        self.trackImgBox.setObjectName(_fromUtf8("trackImgBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.trackImgBox)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.trackMaskBox = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackMaskBox.sizePolicy().hasHeightForWidth())
        self.trackMaskBox.setSizePolicy(sizePolicy)
        self.trackMaskBox.setObjectName(_fromUtf8("trackMaskBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.trackMaskBox)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.paramEdit = QtGui.QLineEdit(self.groupBox_2)
        self.paramEdit.setObjectName(_fromUtf8("paramEdit"))
        self.horizontalLayout_2.addWidget(self.paramEdit)
        self.chooseParamButton = QtGui.QPushButton(self.groupBox_2)
        self.chooseParamButton.setObjectName(_fromUtf8("chooseParamButton"))
        self.horizontalLayout_2.addWidget(self.chooseParamButton)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.trackButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackButton.sizePolicy().hasHeightForWidth())
        self.trackButton.setSizePolicy(sizePolicy)
        self.trackButton.setObjectName(_fromUtf8("trackButton"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.trackButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_6)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.trackObjBox = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackObjBox.sizePolicy().hasHeightForWidth())
        self.trackObjBox.setSizePolicy(sizePolicy)
        self.trackObjBox.setObjectName(_fromUtf8("trackObjBox"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.trackObjBox)
        self.applyTrackButton = QtGui.QPushButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyTrackButton.sizePolicy().hasHeightForWidth())
        self.applyTrackButton.setSizePolicy(sizePolicy)
        self.applyTrackButton.setObjectName(_fromUtf8("applyTrackButton"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.applyTrackButton)
        self.trackDataBox = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackDataBox.sizePolicy().hasHeightForWidth())
        self.trackDataBox.setSizePolicy(sizePolicy)
        self.trackDataBox.setObjectName(_fromUtf8("trackDataBox"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.trackDataBox)
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_3 = QtGui.QGroupBox(CTMotionProp)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_7 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.meshSqueezeBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshSqueezeBox.sizePolicy().hasHeightForWidth())
        self.meshSqueezeBox.setSizePolicy(sizePolicy)
        self.meshSqueezeBox.setObjectName(_fromUtf8("meshSqueezeBox"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.meshSqueezeBox)
        self.squeezeButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.squeezeButton.sizePolicy().hasHeightForWidth())
        self.squeezeButton.setSizePolicy(sizePolicy)
        self.squeezeButton.setObjectName(_fromUtf8("squeezeButton"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.squeezeButton)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.meshMaskGenGroup = QtGui.QGroupBox(CTMotionProp)
        self.meshMaskGenGroup.setObjectName(_fromUtf8("meshMaskGenGroup"))
        self.formLayout = QtGui.QFormLayout(self.meshMaskGenGroup)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.meshMaskGenGroup)
        self.label.setMinimumSize(QtCore.QSize(62, 0))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.meshMaskBox = QtGui.QComboBox(self.meshMaskGenGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meshMaskBox.sizePolicy().hasHeightForWidth())
        self.meshMaskBox.setSizePolicy(sizePolicy)
        self.meshMaskBox.setObjectName(_fromUtf8("meshMaskBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.meshMaskBox)
        self.label_2 = QtGui.QLabel(self.meshMaskGenGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.thresholdBox = QtGui.QDoubleSpinBox(self.meshMaskGenGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdBox.sizePolicy().hasHeightForWidth())
        self.thresholdBox.setSizePolicy(sizePolicy)
        self.thresholdBox.setDecimals(3)
        self.thresholdBox.setMaximum(9999.99)
        self.thresholdBox.setProperty("value", 1.0)
        self.thresholdBox.setObjectName(_fromUtf8("thresholdBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.thresholdBox)
        self.label_3 = QtGui.QLabel(self.meshMaskGenGroup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.smoothBox = QtGui.QSpinBox(self.meshMaskGenGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smoothBox.sizePolicy().hasHeightForWidth())
        self.smoothBox.setSizePolicy(sizePolicy)
        self.smoothBox.setObjectName(_fromUtf8("smoothBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.smoothBox)
        self.resampleCheck = QtGui.QCheckBox(self.meshMaskGenGroup)
        self.resampleCheck.setObjectName(_fromUtf8("resampleCheck"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.resampleCheck)
        self.decimateCheck = QtGui.QCheckBox(self.meshMaskGenGroup)
        self.decimateCheck.setObjectName(_fromUtf8("decimateCheck"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.decimateCheck)
        self.closedCheck = QtGui.QCheckBox(self.meshMaskGenGroup)
        self.closedCheck.setChecked(True)
        self.closedCheck.setObjectName(_fromUtf8("closedCheck"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.closedCheck)
        self.genMeshButton = QtGui.QPushButton(self.meshMaskGenGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genMeshButton.sizePolicy().hasHeightForWidth())
        self.genMeshButton.setSizePolicy(sizePolicy)
        self.genMeshButton.setObjectName(_fromUtf8("genMeshButton"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.genMeshButton)
        self.verticalLayout.addWidget(self.meshMaskGenGroup)

        self.retranslateUi(CTMotionProp)
        QtCore.QMetaObject.connectSlotsByName(CTMotionProp)

    def retranslateUi(self, CTMotionProp):
        CTMotionProp.setWindowTitle(_translate("CTMotionProp", "Form", None))
        self.groupBox.setTitle(_translate("CTMotionProp", "Import Data", None))
        self.ctDicomButton.setText(_translate("CTMotionProp", "CT DICOM Series", None))
        self.niftiButton.setText(_translate("CTMotionProp", "NIfTI Image Stack", None))
        self.groupBox_5.setTitle(_translate("CTMotionProp", "Image Resampling", None))
        self.label_4.setText(_translate("CTMotionProp", "Image Series", None))
        self.label_5.setText(_translate("CTMotionProp", "Voxel Size", None))
        self.srcVoxelLabel.setText(_translate("CTMotionProp", "Source Voxel Size:", None))
        self.isotropicBox.setText(_translate("CTMotionProp", "Isotropic", None))
        self.resampleButton.setText(_translate("CTMotionProp", "Generate", None))
        self.label_6.setText(_translate("CTMotionProp", "X", None))
        self.label_7.setText(_translate("CTMotionProp", "Y", None))
        self.label_8.setText(_translate("CTMotionProp", "Z", None))
        self.groupBox_7.setTitle(_translate("CTMotionProp", "Segmentation", None))
        self.label_14.setText(_translate("CTMotionProp", "Choose Points", None))
        self.show3ptButton.setText(_translate("CTMotionProp", "Show Image 3 Point Picker", None))
        self.label_15.setText(_translate("CTMotionProp", "Image Series", None))
        self.resample3ptButton.setText(_translate("CTMotionProp", "Resample Image", None))
        self.createSegButton.setText(_translate("CTMotionProp", "Create Segmentation Object", None))
        self.groupBox_8.setTitle(_translate("CTMotionProp", "Mesh Generation From Segmentation", None))
        self.label_16.setText(_translate("CTMotionProp", "Segmentation", None))
        self.label_17.setText(_translate("CTMotionProp", "Refinement", None))
        self.genMeshSegButton.setText(_translate("CTMotionProp", "Generate", None))
        self.groupBox_2.setTitle(_translate("CTMotionProp", "Motion Tracking", None))
        self.label_9.setText(_translate("CTMotionProp", "Image Series", None))
        self.label_10.setText(_translate("CTMotionProp", "Mask Image", None))
        self.label_11.setText(_translate("CTMotionProp", "Param File", None))
        self.chooseParamButton.setText(_translate("CTMotionProp", "Choose", None))
        self.trackButton.setText(_translate("CTMotionProp", "Start Motion Tracking", None))
        self.groupBox_6.setTitle(_translate("CTMotionProp", "Apply Tracking", None))
        self.label_12.setText(_translate("CTMotionProp", "Object", None))
        self.applyTrackButton.setText(_translate("CTMotionProp", "Apply Tracking", None))
        self.label_18.setText(_translate("CTMotionProp", "Track Data", None))
        self.groupBox_3.setTitle(_translate("CTMotionProp", "Squeeze Calculation", None))
        self.label_13.setText(_translate("CTMotionProp", "Mesh", None))
        self.squeezeButton.setText(_translate("CTMotionProp", "Calculate", None))
        self.meshMaskGenGroup.setTitle(_translate("CTMotionProp", "Mesh Generation From Mask", None))
        self.label.setText(_translate("CTMotionProp", "Mask Image", None))
        self.label_2.setText(_translate("CTMotionProp", "Threshold", None))
        self.label_3.setText(_translate("CTMotionProp", "Smooth", None))
        self.resampleCheck.setText(_translate("CTMotionProp", "Resample input to isotropic image", None))
        self.decimateCheck.setText(_translate("CTMotionProp", "Decimate output vertices", None))
        self.closedCheck.setText(_translate("CTMotionProp", "Closed surface", None))
        self.genMeshButton.setText(_translate("CTMotionProp", "Generate", None))

