# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/MainWindow.ui'
#
# Created: Wed Sep  6 15:42:09 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(872, 859)
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mainLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setMargin(0)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.viz = QtGui.QWidget(self.centralwidget)
        self.viz.setEnabled(True)
        self.viz.setObjectName(_fromUtf8("viz"))
        self.mainLayout.addWidget(self.viz)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_New_Project = QtGui.QMenu(self.menuFile)
        self.menu_New_Project.setObjectName(_fromUtf8("menu_New_Project"))
        self.menuImport = QtGui.QMenu(self.menubar)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menuCreate = QtGui.QMenu(self.menubar)
        self.menuCreate.setObjectName(_fromUtf8("menuCreate"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuExport = QtGui.QMenu(self.menubar)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.interfaceDock = QtGui.QDockWidget(MainWindow)
        self.interfaceDock.setMinimumSize(QtCore.QSize(412, 596))
        self.interfaceDock.setToolTip(_fromUtf8(""))
        self.interfaceDock.setAccessibleName(_fromUtf8(""))
        self.interfaceDock.setFloating(False)
        self.interfaceDock.setObjectName(_fromUtf8("interfaceDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.interfaceTab = QtGui.QTabWidget(self.dockWidgetContents)
        self.interfaceTab.setObjectName(_fromUtf8("interfaceTab"))
        self.sceneTab = QtGui.QWidget()
        self.sceneTab.setObjectName(_fromUtf8("sceneTab"))
        self.gridLayout = QtGui.QGridLayout(self.sceneTab)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.treeGroup = QtGui.QGroupBox(self.sceneTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeGroup.sizePolicy().hasHeightForWidth())
        self.treeGroup.setSizePolicy(sizePolicy)
        self.treeGroup.setMinimumSize(QtCore.QSize(0, 0))
        self.treeGroup.setObjectName(_fromUtf8("treeGroup"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.treeGroup)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 6, 4, 6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeWidget = QtGui.QTreeWidget(self.treeGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.treeWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setDefaultSectionSize(30)
        self.treeWidget.header().setMinimumSectionSize(20)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.removeObjectButton = QtGui.QPushButton(self.treeGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeObjectButton.sizePolicy().hasHeightForWidth())
        self.removeObjectButton.setSizePolicy(sizePolicy)
        self.removeObjectButton.setMaximumSize(QtCore.QSize(28, 28))
        self.removeObjectButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/trash-a.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeObjectButton.setIcon(icon)
        self.removeObjectButton.setIconSize(QtCore.QSize(24, 24))
        self.removeObjectButton.setObjectName(_fromUtf8("removeObjectButton"))
        self.horizontalLayout_6.addWidget(self.removeObjectButton)
        spacerItem = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.renameButton = QtGui.QPushButton(self.treeGroup)
        self.renameButton.setMaximumSize(QtCore.QSize(28, 28))
        self.renameButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/nametag.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.renameButton.setIcon(icon1)
        self.renameButton.setIconSize(QtCore.QSize(24, 24))
        self.renameButton.setObjectName(_fromUtf8("renameButton"))
        self.horizontalLayout_6.addWidget(self.renameButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.clearButton = QtGui.QPushButton(self.treeGroup)
        self.clearButton.setMaximumSize(QtCore.QSize(28, 28))
        self.clearButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/close-circled.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon2)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_6.addWidget(self.clearButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.treeGroup, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.seeAllButton = QtGui.QPushButton(self.sceneTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seeAllButton.sizePolicy().hasHeightForWidth())
        self.seeAllButton.setSizePolicy(sizePolicy)
        self.seeAllButton.setMinimumSize(QtCore.QSize(120, 0))
        self.seeAllButton.setObjectName(_fromUtf8("seeAllButton"))
        self.horizontalLayout_7.addWidget(self.seeAllButton)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.propScrollArea = QtGui.QScrollArea(self.sceneTab)
        self.propScrollArea.setMinimumSize(QtCore.QSize(0, 50))
        self.propScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propScrollArea.setWidgetResizable(True)
        self.propScrollArea.setObjectName(_fromUtf8("propScrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 459, 235))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.propScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.propScrollArea, 4, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/camera.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.interfaceTab.addTab(self.sceneTab, icon3, _fromUtf8(""))
        self.assetsTab = QtGui.QWidget()
        self.assetsTab.setObjectName(_fromUtf8("assetsTab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.assetsTab)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.assetScrollArea = QtGui.QScrollArea(self.assetsTab)
        self.assetScrollArea.setWidgetResizable(True)
        self.assetScrollArea.setObjectName(_fromUtf8("assetScrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 459, 251))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.assetScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.addWidget(self.assetScrollArea, 4, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.loadShaderButton = QtGui.QPushButton(self.assetsTab)
        self.loadShaderButton.setObjectName(_fromUtf8("loadShaderButton"))
        self.gridLayout_3.addWidget(self.loadShaderButton, 1, 1, 1, 1)
        self.loadTextureButton = QtGui.QPushButton(self.assetsTab)
        self.loadTextureButton.setObjectName(_fromUtf8("loadTextureButton"))
        self.gridLayout_3.addWidget(self.loadTextureButton, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.assetList = QtGui.QTreeWidget(self.assetsTab)
        self.assetList.setMaximumSize(QtCore.QSize(16777215, 200))
        self.assetList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.assetList.setAutoExpandDelay(-1)
        self.assetList.setObjectName(_fromUtf8("assetList"))
        self.assetList.header().setVisible(False)
        self.gridLayout_5.addWidget(self.assetList, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.removeAssetButton = QtGui.QPushButton(self.assetsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeAssetButton.sizePolicy().hasHeightForWidth())
        self.removeAssetButton.setSizePolicy(sizePolicy)
        self.removeAssetButton.setMinimumSize(QtCore.QSize(0, 0))
        self.removeAssetButton.setMaximumSize(QtCore.QSize(28, 28))
        self.removeAssetButton.setText(_fromUtf8(""))
        self.removeAssetButton.setIcon(icon)
        self.removeAssetButton.setIconSize(QtCore.QSize(24, 24))
        self.removeAssetButton.setDefault(False)
        self.removeAssetButton.setFlat(False)
        self.removeAssetButton.setObjectName(_fromUtf8("removeAssetButton"))
        self.horizontalLayout.addWidget(self.removeAssetButton)
        self.cloneButton = QtGui.QPushButton(self.assetsTab)
        self.cloneButton.setMaximumSize(QtCore.QSize(28, 28))
        self.cloneButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/clone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cloneButton.setIcon(icon4)
        self.cloneButton.setIconSize(QtCore.QSize(24, 24))
        self.cloneButton.setObjectName(_fromUtf8("cloneButton"))
        self.horizontalLayout.addWidget(self.cloneButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.newSpecButton = QtGui.QPushButton(self.assetsTab)
        self.newSpecButton.setObjectName(_fromUtf8("newSpecButton"))
        self.horizontalLayout.addWidget(self.newSpecButton)
        self.newMatButton = QtGui.QPushButton(self.assetsTab)
        self.newMatButton.setObjectName(_fromUtf8("newMatButton"))
        self.horizontalLayout.addWidget(self.newMatButton)
        self.newLightButton = QtGui.QPushButton(self.assetsTab)
        self.newLightButton.setObjectName(_fromUtf8("newLightButton"))
        self.horizontalLayout.addWidget(self.newLightButton)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gear-b.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.interfaceTab.addTab(self.assetsTab, icon5, _fromUtf8(""))
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName(_fromUtf8("configTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.configTab)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.configTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setMargin(6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.nearClipBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.nearClipBox.setDecimals(6)
        self.nearClipBox.setMaximum(99999999.99)
        self.nearClipBox.setObjectName(_fromUtf8("nearClipBox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.nearClipBox)
        self.farClipBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.farClipBox.setDecimals(6)
        self.farClipBox.setMaximum(99999999.99)
        self.farClipBox.setObjectName(_fromUtf8("farClipBox"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.farClipBox)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.fovBox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.fovBox.setDecimals(5)
        self.fovBox.setMinimum(1e-05)
        self.fovBox.setMaximum(1.0)
        self.fovBox.setSingleStep(0.001)
        self.fovBox.setObjectName(_fromUtf8("fovBox"))
        self.horizontalLayout_4.addWidget(self.fovBox)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.gridLayout_6.addLayout(self.formLayout_3, 4, 1, 1, 1)
        self.orthoCheck = QtGui.QCheckBox(self.groupBox_2)
        self.orthoCheck.setObjectName(_fromUtf8("orthoCheck"))
        self.gridLayout_6.addWidget(self.orthoCheck, 2, 1, 1, 1)
        self.cameraProps = QtGui.QTableWidget(self.groupBox_2)
        self.cameraProps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cameraProps.setAutoFillBackground(False)
        self.cameraProps.setAlternatingRowColors(True)
        self.cameraProps.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.cameraProps.setTextElideMode(QtCore.Qt.ElideNone)
        self.cameraProps.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.cameraProps.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.cameraProps.setShowGrid(False)
        self.cameraProps.setObjectName(_fromUtf8("cameraProps"))
        self.cameraProps.setColumnCount(2)
        self.cameraProps.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cameraProps.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cameraProps.setHorizontalHeaderItem(1, item)
        self.cameraProps.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.cameraProps, 0, 1, 1, 1)
        self.wireframeCheck = QtGui.QCheckBox(self.groupBox_2)
        self.wireframeCheck.setObjectName(_fromUtf8("wireframeCheck"))
        self.gridLayout_6.addWidget(self.wireframeCheck, 1, 1, 1, 1)
        self.zLockCheck = QtGui.QCheckBox(self.groupBox_2)
        self.zLockCheck.setChecked(True)
        self.zLockCheck.setObjectName(_fromUtf8("zLockCheck"))
        self.gridLayout_6.addWidget(self.zLockCheck, 3, 1, 1, 1)
        self.camResetButton = QtGui.QPushButton(self.groupBox_2)
        self.camResetButton.setObjectName(_fromUtf8("camResetButton"))
        self.gridLayout_6.addWidget(self.camResetButton, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.configTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.axestypeBox = QtGui.QComboBox(self.groupBox_3)
        self.axestypeBox.setObjectName(_fromUtf8("axestypeBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.axestypeBox)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.centertypeBox = QtGui.QComboBox(self.groupBox_3)
        self.centertypeBox.setObjectName(_fromUtf8("centertypeBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.centertypeBox)
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.configTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.highqualCheck = QtGui.QCheckBox(self.groupBox)
        self.highqualCheck.setObjectName(_fromUtf8("highqualCheck"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.highqualCheck)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.chooseAmbient = QtGui.QPushButton(self.groupBox)
        self.chooseAmbient.setMinimumSize(QtCore.QSize(0, 0))
        self.chooseAmbient.setObjectName(_fromUtf8("chooseAmbient"))
        self.horizontalLayout_5.addWidget(self.chooseAmbient)
        self.chooseBackground = QtGui.QPushButton(self.groupBox)
        self.chooseBackground.setObjectName(_fromUtf8("chooseBackground"))
        self.horizontalLayout_5.addWidget(self.chooseBackground)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/wrench.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.interfaceTab.addTab(self.configTab, icon6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.interfaceTab)
        self.interfaceDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.interfaceDock)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.consoleWidget = QtGui.QDockWidget(MainWindow)
        self.consoleWidget.setMinimumSize(QtCore.QSize(89, 111))
        self.consoleWidget.setObjectName(_fromUtf8("consoleWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.consoleLayout = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.consoleLayout.setObjectName(_fromUtf8("consoleLayout"))
        self.consoleWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.consoleWidget)
        self.timeWidget = QtGui.QDockWidget(MainWindow)
        self.timeWidget.setObjectName(_fromUtf8("timeWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents_3.setSizePolicy(sizePolicy)
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setContentsMargins(4, 0, 4, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.timestepBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.timestepBox.setDecimals(3)
        self.timestepBox.setSingleStep(0.01)
        self.timestepBox.setObjectName(_fromUtf8("timestepBox"))
        self.horizontalLayout_3.addWidget(self.timestepBox)
        self.timestepSlider = QtGui.QSlider(self.dockWidgetContents_3)
        self.timestepSlider.setMaximum(1)
        self.timestepSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timestepSlider.setInvertedControls(False)
        self.timestepSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.timestepSlider.setTickInterval(100)
        self.timestepSlider.setObjectName(_fromUtf8("timestepSlider"))
        self.horizontalLayout_3.addWidget(self.timestepSlider)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.stopButton = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(20, 0))
        self.stopButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.stopButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon7)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.forwardButton = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardButton.sizePolicy().hasHeightForWidth())
        self.forwardButton.setSizePolicy(sizePolicy)
        self.forwardButton.setMinimumSize(QtCore.QSize(20, 0))
        self.forwardButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.forwardButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon8)
        self.forwardButton.setObjectName(_fromUtf8("forwardButton"))
        self.horizontalLayout_2.addWidget(self.forwardButton)
        self.decTimeButton = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decTimeButton.sizePolicy().hasHeightForWidth())
        self.decTimeButton.setSizePolicy(sizePolicy)
        self.decTimeButton.setMinimumSize(QtCore.QSize(20, 0))
        self.decTimeButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.decTimeButton.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/chevron-left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.decTimeButton.setIcon(icon9)
        self.decTimeButton.setObjectName(_fromUtf8("decTimeButton"))
        self.horizontalLayout_2.addWidget(self.decTimeButton)
        self.incTimeButton = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.incTimeButton.sizePolicy().hasHeightForWidth())
        self.incTimeButton.setSizePolicy(sizePolicy)
        self.incTimeButton.setMinimumSize(QtCore.QSize(20, 0))
        self.incTimeButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.incTimeButton.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/chevron-right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.incTimeButton.setIcon(icon10)
        self.incTimeButton.setObjectName(_fromUtf8("incTimeButton"))
        self.horizontalLayout_2.addWidget(self.incTimeButton)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.fpsBox = QtGui.QSpinBox(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fpsBox.sizePolicy().hasHeightForWidth())
        self.fpsBox.setSizePolicy(sizePolicy)
        self.fpsBox.setProperty("value", 25)
        self.fpsBox.setObjectName(_fromUtf8("fpsBox"))
        self.horizontalLayout_2.addWidget(self.fpsBox)
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.stepspersecBox = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.stepspersecBox.setDecimals(2)
        self.stepspersecBox.setMaximum(9999.99)
        self.stepspersecBox.setSingleStep(1.0)
        self.stepspersecBox.setProperty("value", 1.0)
        self.stepspersecBox.setObjectName(_fromUtf8("stepspersecBox"))
        self.horizontalLayout_2.addWidget(self.stepspersecBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.timeWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.timeWidget)
        self.scratchWidget = QtGui.QDockWidget(MainWindow)
        self.scratchWidget.setObjectName(_fromUtf8("scratchWidget"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scratchEdit = QtGui.QPlainTextEdit(self.dockWidgetContents_4)
        self.scratchEdit.setTabStopWidth(20)
        self.scratchEdit.setBackgroundVisible(False)
        self.scratchEdit.setObjectName(_fromUtf8("scratchEdit"))
        self.verticalLayout_4.addWidget(self.scratchEdit)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.execButton = QtGui.QPushButton(self.dockWidgetContents_4)
        self.execButton.setObjectName(_fromUtf8("execButton"))
        self.horizontalLayout_8.addWidget(self.execButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.loadScratchButton = QtGui.QPushButton(self.dockWidgetContents_4)
        self.loadScratchButton.setObjectName(_fromUtf8("loadScratchButton"))
        self.horizontalLayout_8.addWidget(self.loadScratchButton)
        self.saveScratchButton = QtGui.QPushButton(self.dockWidgetContents_4)
        self.saveScratchButton.setObjectName(_fromUtf8("saveScratchButton"))
        self.horizontalLayout_8.addWidget(self.saveScratchButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.scratchWidget.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.scratchWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.actionTake_Screenshot = QtGui.QAction(MainWindow)
        self.actionTake_Screenshot.setObjectName(_fromUtf8("actionTake_Screenshot"))
        self.action_Scene_Elements = QtGui.QAction(MainWindow)
        self.action_Scene_Elements.setObjectName(_fromUtf8("action_Scene_Elements"))
        self.action_Console = QtGui.QAction(MainWindow)
        self.action_Console.setObjectName(_fromUtf8("action_Console"))
        self.action_Open_Script = QtGui.QAction(MainWindow)
        self.action_Open_Script.setObjectName(_fromUtf8("action_Open_Script"))
        self.action_Time = QtGui.QAction(MainWindow)
        self.action_Time.setObjectName(_fromUtf8("action_Time"))
        self.actionEnable_Tracing = QtGui.QAction(MainWindow)
        self.actionEnable_Tracing.setObjectName(_fromUtf8("actionEnable_Tracing"))
        self.actionEnable_Logging = QtGui.QAction(MainWindow)
        self.actionEnable_Logging.setObjectName(_fromUtf8("actionEnable_Logging"))
        self.actionShow_Log_Window = QtGui.QAction(MainWindow)
        self.actionShow_Log_Window.setObjectName(_fromUtf8("actionShow_Log_Window"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.action_Save_Script = QtGui.QAction(MainWindow)
        self.action_Save_Script.setObjectName(_fromUtf8("action_Save_Script"))
        self.action_Default_Project = QtGui.QAction(MainWindow)
        self.action_Default_Project.setObjectName(_fromUtf8("action_Default_Project"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionShow_Scene_Code = QtGui.QAction(MainWindow)
        self.actionShow_Scene_Code.setObjectName(_fromUtf8("actionShow_Scene_Code"))
        self.actionScratch_Pad = QtGui.QAction(MainWindow)
        self.actionScratch_Pad.setObjectName(_fromUtf8("actionScratch_Pad"))
        self.actionGC_Collect = QtGui.QAction(MainWindow)
        self.actionGC_Collect.setObjectName(_fromUtf8("actionGC_Collect"))
        self.menu_New_Project.addAction(self.action_Default_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menu_New_Project.menuAction())
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Open_Script)
        self.menuFile.addAction(self.action_Save_Script)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionTake_Screenshot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Quit)
        self.menu_View.addAction(self.action_Scene_Elements)
        self.menu_View.addAction(self.action_Console)
        self.menu_View.addAction(self.action_Time)
        self.menu_View.addAction(self.actionScratch_Pad)
        self.menuOptions.addAction(self.actionShow_Log_Window)
        self.menuOptions.addAction(self.actionShow_Scene_Code)
        self.menuOptions.addAction(self.actionEnable_Logging)
        self.menuOptions.addAction(self.actionEnable_Tracing)
        self.menuOptions.addAction(self.actionGC_Collect)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuCreate.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.interfaceTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menu_New_Project.setTitle(_translate("MainWindow", "&New Project", None))
        self.menuImport.setTitle(_translate("MainWindow", "&Import", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menuCreate.setTitle(_translate("MainWindow", "Create", None))
        self.menuOptions.setTitle(_translate("MainWindow", "&Options", None))
        self.menuExport.setTitle(_translate("MainWindow", "Export", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.interfaceDock.setWindowTitle(_translate("MainWindow", "Scene Elements", None))
        self.treeGroup.setToolTip(_translate("MainWindow", "Loaded scene objects", None))
        self.treeGroup.setTitle(_translate("MainWindow", "Objects", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Objects", None))
        self.removeObjectButton.setToolTip(_translate("MainWindow", "Remove Scene Object", None))
        self.renameButton.setToolTip(_translate("MainWindow", "Rename Scene Object", None))
        self.clearButton.setToolTip(_translate("MainWindow", "Clear Scene", None))
        self.seeAllButton.setToolTip(_translate("MainWindow", "Reset scene camera to show all visible objects", None))
        self.seeAllButton.setText(_translate("MainWindow", "See All", None))
        self.interfaceTab.setTabText(self.interfaceTab.indexOf(self.sceneTab), _translate("MainWindow", "Scene", None))
        self.interfaceTab.setTabToolTip(self.interfaceTab.indexOf(self.sceneTab), _translate("MainWindow", "View and manipulate data objects loaded into the scene", None))
        self.loadShaderButton.setText(_translate("MainWindow", "Load GPU Script", None))
        self.loadTextureButton.setText(_translate("MainWindow", "Load Texture", None))
        self.assetList.headerItem().setText(0, _translate("MainWindow", "Objects", None))
        self.removeAssetButton.setToolTip(_translate("MainWindow", "Remove Asset", None))
        self.cloneButton.setToolTip(_translate("MainWindow", "Clone Asset", None))
        self.newSpecButton.setText(_translate("MainWindow", "New Spectrum", None))
        self.newMatButton.setText(_translate("MainWindow", "New Material", None))
        self.newLightButton.setText(_translate("MainWindow", "New Light", None))
        self.interfaceTab.setTabText(self.interfaceTab.indexOf(self.assetsTab), _translate("MainWindow", "Assets", None))
        self.interfaceTab.setTabToolTip(self.interfaceTab.indexOf(self.assetsTab), _translate("MainWindow", "View and manipulate scene assets", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Camera", None))
        self.label.setText(_translate("MainWindow", "Vertical FOV", None))
        self.label_9.setText(_translate("MainWindow", "Near Clip Dist", None))
        self.label_10.setText(_translate("MainWindow", "Far Clip Dist", None))
        self.label_11.setText(_translate("MainWindow", "×π", None))
        self.orthoCheck.setText(_translate("MainWindow", "Camera Orthographic", None))
        item = self.cameraProps.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.cameraProps.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        self.wireframeCheck.setText(_translate("MainWindow", "Camera Wireframe Mode", None))
        self.zLockCheck.setText(_translate("MainWindow", "Camera Z-Lock", None))
        self.camResetButton.setText(_translate("MainWindow", "Reset", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Axes && Markers", None))
        self.label_2.setText(_translate("MainWindow", "Axes Type", None))
        self.label_3.setText(_translate("MainWindow", "Center Marker", None))
        self.groupBox.setTitle(_translate("MainWindow", "Scene Config", None))
        self.highqualCheck.setText(_translate("MainWindow", "Always Render High Quality", None))
        self.chooseAmbient.setText(_translate("MainWindow", "Ambient Light", None))
        self.chooseBackground.setText(_translate("MainWindow", "Background Color", None))
        self.interfaceTab.setTabText(self.interfaceTab.indexOf(self.configTab), _translate("MainWindow", "Config", None))
        self.interfaceTab.setTabToolTip(self.interfaceTab.indexOf(self.configTab), _translate("MainWindow", "Modify configuration settings for scene", None))
        self.consoleWidget.setToolTip(_translate("MainWindow", "Python runtime console", None))
        self.consoleWidget.setWindowTitle(_translate("MainWindow", "Console", None))
        self.timeWidget.setToolTip(_translate("MainWindow", "Time controls", None))
        self.timeWidget.setWindowTitle(_translate("MainWindow", "Time", None))
        self.label_4.setText(_translate("MainWindow", "Timestep:", None))
        self.timestepBox.setToolTip(_translate("MainWindow", "Current timestep", None))
        self.timestepSlider.setToolTip(_translate("MainWindow", "Move timestep", None))
        self.stopButton.setToolTip(_translate("MainWindow", "Stop Playback", None))
        self.forwardButton.setToolTip(_translate("MainWindow", "Start Playback", None))
        self.decTimeButton.setToolTip(_translate("MainWindow", "Step Time Backward", None))
        self.incTimeButton.setToolTip(_translate("MainWindow", "Step Time Forward", None))
        self.label_5.setText(_translate("MainWindow", "Frames/s", None))
        self.fpsBox.setToolTip(_translate("MainWindow", "Frames per second", None))
        self.label_6.setText(_translate("MainWindow", "Steps/s", None))
        self.stepspersecBox.setToolTip(_translate("MainWindow", "Timesteps per second", None))
        self.scratchWidget.setToolTip(_translate("MainWindow", "Scratch pad for script code", None))
        self.scratchWidget.setWindowTitle(_translate("MainWindow", "Scratch Pad", None))
        self.execButton.setToolTip(_translate("MainWindow", "Execute code in console", None))
        self.execButton.setText(_translate("MainWindow", "&Execute", None))
        self.loadScratchButton.setToolTip(_translate("MainWindow", "Open text file", None))
        self.loadScratchButton.setText(_translate("MainWindow", "&Open", None))
        self.saveScratchButton.setToolTip(_translate("MainWindow", "Save to text file", None))
        self.saveScratchButton.setText(_translate("MainWindow", "&Save", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.actionTake_Screenshot.setText(_translate("MainWindow", "&Take Screenshot(s)", None))
        self.action_Scene_Elements.setText(_translate("MainWindow", "&Scene Elements", None))
        self.action_Console.setText(_translate("MainWindow", "&Console", None))
        self.action_Open_Script.setText(_translate("MainWindow", "&Open Script", None))
        self.action_Time.setText(_translate("MainWindow", "&Time", None))
        self.actionEnable_Tracing.setText(_translate("MainWindow", "Enable &Tracing", None))
        self.actionEnable_Logging.setText(_translate("MainWindow", "Enable &Logging", None))
        self.actionShow_Log_Window.setText(_translate("MainWindow", "&Show Log Window", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open &Project", None))
        self.action_Save_Script.setText(_translate("MainWindow", "&Save Script", None))
        self.action_Default_Project.setText(_translate("MainWindow", "&Default Project", None))
        self.action_About.setText(_translate("MainWindow", "&Aboot", None))
        self.actionSave_Project.setText(_translate("MainWindow", "Sa&ve Project", None))
        self.actionShow_Scene_Code.setText(_translate("MainWindow", "Show Scene &Code", None))
        self.actionScratch_Pad.setText(_translate("MainWindow", "Scratch &Pad", None))
        self.actionGC_Collect.setText(_translate("MainWindow", "GC Collect", None))

import Resources_rc
