# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/MatProp.ui'
#
# Created: Mon Oct 17 15:55:12 2016
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_matProp(object):
    def setupUi(self, matProp):
        matProp.setObjectName(_fromUtf8("matProp"))
        matProp.resize(367, 914)
        self.verticalLayout = QtGui.QVBoxLayout(matProp)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.applyButton = QtGui.QPushButton(matProp)
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.verticalLayout.addWidget(self.applyButton)
        self.groupBox = QtGui.QGroupBox(matProp)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.chooseDiffuse = QtGui.QPushButton(self.groupBox)
        self.chooseDiffuse.setMinimumSize(QtCore.QSize(80, 0))
        self.chooseDiffuse.setMaximumSize(QtCore.QSize(70, 16777215))
        self.chooseDiffuse.setObjectName(_fromUtf8("chooseDiffuse"))
        self.gridLayout_2.addWidget(self.chooseDiffuse, 1, 1, 1, 1)
        self.chooseSpecular = QtGui.QPushButton(self.groupBox)
        self.chooseSpecular.setMinimumSize(QtCore.QSize(80, 0))
        self.chooseSpecular.setMaximumSize(QtCore.QSize(70, 16777215))
        self.chooseSpecular.setObjectName(_fromUtf8("chooseSpecular"))
        self.gridLayout_2.addWidget(self.chooseSpecular, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.alphaBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.alphaBox.setDecimals(3)
        self.alphaBox.setMaximum(1.0)
        self.alphaBox.setSingleStep(0.1)
        self.alphaBox.setProperty("value", 1.0)
        self.alphaBox.setObjectName(_fromUtf8("alphaBox"))
        self.horizontalLayout_2.addWidget(self.alphaBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.shininessBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.shininessBox.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.shininessBox.setDecimals(1)
        self.shininessBox.setMaximum(9999.0)
        self.shininessBox.setObjectName(_fromUtf8("shininessBox"))
        self.horizontalLayout.addWidget(self.shininessBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.chooseAmbient = QtGui.QPushButton(self.groupBox)
        self.chooseAmbient.setMinimumSize(QtCore.QSize(80, 0))
        self.chooseAmbient.setMaximumSize(QtCore.QSize(70, 16777215))
        self.chooseAmbient.setObjectName(_fromUtf8("chooseAmbient"))
        self.gridLayout_2.addWidget(self.chooseAmbient, 1, 0, 1, 1)
        self.chooseEmissive = QtGui.QPushButton(self.groupBox)
        self.chooseEmissive.setMinimumSize(QtCore.QSize(80, 0))
        self.chooseEmissive.setMaximumSize(QtCore.QSize(70, 16777215))
        self.chooseEmissive.setObjectName(_fromUtf8("chooseEmissive"))
        self.gridLayout_2.addWidget(self.chooseEmissive, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.spectrumBox = QtGui.QGroupBox(matProp)
        self.spectrumBox.setFlat(False)
        self.spectrumBox.setObjectName(_fromUtf8("spectrumBox"))
        self.gridLayout = QtGui.QGridLayout(self.spectrumBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spectrum = QtGui.QWidget(self.spectrumBox)
        self.spectrum.setMinimumSize(QtCore.QSize(0, 20))
        self.spectrum.setObjectName(_fromUtf8("spectrum"))
        self.gridLayout.addWidget(self.spectrum, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.spectrumBox)
        self.groupBox_4 = QtGui.QGroupBox(matProp)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.spectrumList = QtGui.QComboBox(self.groupBox_4)
        self.spectrumList.setObjectName(_fromUtf8("spectrumList"))
        self.horizontalLayout_5.addWidget(self.spectrumList)
        self.setSpecButton = QtGui.QPushButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setSpecButton.sizePolicy().hasHeightForWidth())
        self.setSpecButton.setSizePolicy(sizePolicy)
        self.setSpecButton.setObjectName(_fromUtf8("setSpecButton"))
        self.horizontalLayout_5.addWidget(self.setSpecButton)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_9 = QtGui.QGroupBox(matProp)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.useLightingCheck = QtGui.QCheckBox(self.groupBox_9)
        self.useLightingCheck.setChecked(True)
        self.useLightingCheck.setObjectName(_fromUtf8("useLightingCheck"))
        self.verticalLayout_5.addWidget(self.useLightingCheck)
        self.flatShadingCheck = QtGui.QCheckBox(self.groupBox_9)
        self.flatShadingCheck.setChecked(True)
        self.flatShadingCheck.setObjectName(_fromUtf8("flatShadingCheck"))
        self.verticalLayout_5.addWidget(self.flatShadingCheck)
        self.useVertexCheck = QtGui.QCheckBox(self.groupBox_9)
        self.useVertexCheck.setChecked(True)
        self.useVertexCheck.setObjectName(_fromUtf8("useVertexCheck"))
        self.verticalLayout_5.addWidget(self.useVertexCheck)
        self.useSpritesCheck = QtGui.QCheckBox(self.groupBox_9)
        self.useSpritesCheck.setChecked(True)
        self.useSpritesCheck.setObjectName(_fromUtf8("useSpritesCheck"))
        self.verticalLayout_5.addWidget(self.useSpritesCheck)
        self.cullBackfacesCheck = QtGui.QCheckBox(self.groupBox_9)
        self.cullBackfacesCheck.setChecked(True)
        self.cullBackfacesCheck.setObjectName(_fromUtf8("cullBackfacesCheck"))
        self.verticalLayout_5.addWidget(self.cullBackfacesCheck)
        self.depthCheck = QtGui.QCheckBox(self.groupBox_9)
        self.depthCheck.setChecked(True)
        self.depthCheck.setObjectName(_fromUtf8("depthCheck"))
        self.verticalLayout_5.addWidget(self.depthCheck)
        self.depthWriteCheck = QtGui.QCheckBox(self.groupBox_9)
        self.depthWriteCheck.setChecked(True)
        self.depthWriteCheck.setObjectName(_fromUtf8("depthWriteCheck"))
        self.verticalLayout_5.addWidget(self.depthWriteCheck)
        self.texFilterCheck = QtGui.QCheckBox(self.groupBox_9)
        self.texFilterCheck.setChecked(True)
        self.texFilterCheck.setObjectName(_fromUtf8("texFilterCheck"))
        self.verticalLayout_5.addWidget(self.texFilterCheck)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_7 = QtGui.QGroupBox(matProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.absoluteRadio = QtGui.QRadioButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.absoluteRadio.sizePolicy().hasHeightForWidth())
        self.absoluteRadio.setSizePolicy(sizePolicy)
        self.absoluteRadio.setChecked(True)
        self.absoluteRadio.setObjectName(_fromUtf8("absoluteRadio"))
        self.horizontalLayout_3.addWidget(self.absoluteRadio)
        self.absSizeBox = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.absSizeBox.setDecimals(4)
        self.absSizeBox.setSingleStep(0.001)
        self.absSizeBox.setProperty("value", 1.0)
        self.absSizeBox.setObjectName(_fromUtf8("absSizeBox"))
        self.horizontalLayout_3.addWidget(self.absSizeBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.relativeRadio = QtGui.QRadioButton(self.groupBox_7)
        self.relativeRadio.setChecked(False)
        self.relativeRadio.setObjectName(_fromUtf8("relativeRadio"))
        self.verticalLayout_7.addWidget(self.relativeRadio)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.minSizeBox = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.minSizeBox.setDecimals(4)
        self.minSizeBox.setSingleStep(0.001)
        self.minSizeBox.setProperty("value", 1.0)
        self.minSizeBox.setObjectName(_fromUtf8("minSizeBox"))
        self.horizontalLayout_4.addWidget(self.minSizeBox)
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.maxSizeBox = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.maxSizeBox.setDecimals(4)
        self.maxSizeBox.setSingleStep(0.001)
        self.maxSizeBox.setProperty("value", 1.0)
        self.maxSizeBox.setObjectName(_fromUtf8("maxSizeBox"))
        self.horizontalLayout_4.addWidget(self.maxSizeBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(matProp)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textureList = QtGui.QComboBox(self.groupBox_8)
        self.textureList.setObjectName(_fromUtf8("textureList"))
        self.verticalLayout_4.addWidget(self.textureList)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_2 = QtGui.QGroupBox(matProp)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fragList = QtGui.QComboBox(self.groupBox_2)
        self.fragList.setObjectName(_fromUtf8("fragList"))
        self.verticalLayout_2.addWidget(self.fragList)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(matProp)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.vertList = QtGui.QComboBox(self.groupBox_3)
        self.vertList.setObjectName(_fromUtf8("vertList"))
        self.verticalLayout_3.addWidget(self.vertList)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.geomBox = QtGui.QGroupBox(matProp)
        self.geomBox.setObjectName(_fromUtf8("geomBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.geomBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.geomList = QtGui.QComboBox(self.geomBox)
        self.geomList.setObjectName(_fromUtf8("geomList"))
        self.verticalLayout_6.addWidget(self.geomList)
        self.verticalLayout.addWidget(self.geomBox)

        self.retranslateUi(matProp)
        QtCore.QMetaObject.connectSlotsByName(matProp)

    def retranslateUi(self, matProp):
        matProp.setWindowTitle(_translate("matProp", "Form", None))
        self.applyButton.setText(_translate("matProp", "Apply Changes", None))
        self.groupBox.setTitle(_translate("matProp", "Colors", None))
        self.chooseDiffuse.setToolTip(_translate("matProp", "Set the diffuse color", None))
        self.chooseDiffuse.setText(_translate("matProp", "Diffuse", None))
        self.chooseSpecular.setToolTip(_translate("matProp", "Set the specular color", None))
        self.chooseSpecular.setText(_translate("matProp", "Specular", None))
        self.label_10.setText(_translate("matProp", "Transparency", None))
        self.alphaBox.setToolTip(_translate("matProp", "Set the transparency for the whole object (1.0 == opaque, 0.0 == invisible)", None))
        self.label_9.setText(_translate("matProp", "Shininess", None))
        self.shininessBox.setToolTip(_translate("matProp", "Set the shininess value for specular highlights (high values == more concentrated)", None))
        self.chooseAmbient.setToolTip(_translate("matProp", "Set the ambient color", None))
        self.chooseAmbient.setText(_translate("matProp", "Ambient", None))
        self.chooseEmissive.setToolTip(_translate("matProp", "Set the emissive color", None))
        self.chooseEmissive.setText(_translate("matProp", "Emissive", None))
        self.spectrumBox.setTitle(_translate("matProp", "Spectrum", None))
        self.groupBox_4.setTitle(_translate("matProp", "Set Spectrum", None))
        self.setSpecButton.setText(_translate("matProp", "Set", None))
        self.groupBox_9.setTitle(_translate("matProp", "Properties", None))
        self.useLightingCheck.setToolTip(_translate("matProp", "Toggles the use of lighting to shade objects", None))
        self.useLightingCheck.setText(_translate("matProp", "Use Lighting", None))
        self.flatShadingCheck.setToolTip(_translate("matProp", "Toggles smooth or flat shading over triangle surfaces", None))
        self.flatShadingCheck.setText(_translate("matProp", "Flat Shading", None))
        self.useVertexCheck.setToolTip(_translate("matProp", "Toggles whether vertex color information is used for color composition", None))
        self.useVertexCheck.setText(_translate("matProp", "Use Vertex Colors", None))
        self.useSpritesCheck.setText(_translate("matProp", "Use Point Sprites", None))
        self.cullBackfacesCheck.setToolTip(_translate("matProp", "Toggles whether triangles facing away from the camera are rendered", None))
        self.cullBackfacesCheck.setText(_translate("matProp", "Cull Backfaces", None))
        self.depthCheck.setToolTip(_translate("matProp", "Toggles depth checking when rendering, off implies object draw over top previous renders", None))
        self.depthCheck.setText(_translate("matProp", "Depth Check", None))
        self.depthWriteCheck.setToolTip(_translate("matProp", "Toggles whether depth information is updated when objects are drawn", None))
        self.depthWriteCheck.setText(_translate("matProp", "Depth Write", None))
        self.texFilterCheck.setToolTip(_translate("matProp", "Toggles bilinear texture filtering, off provides an accurate data representation", None))
        self.texFilterCheck.setText(_translate("matProp", "Texture Filtering", None))
        self.groupBox_7.setTitle(_translate("matProp", "Point Sizes", None))
        self.absoluteRadio.setToolTip(_translate("matProp", "Sets to use absolute point size", None))
        self.absoluteRadio.setText(_translate("matProp", "Absolute Size", None))
        self.absSizeBox.setToolTip(_translate("matProp", "Sets the absolute size of points", None))
        self.relativeRadio.setToolTip(_translate("matProp", "Sets to use varying point size dependent on camera distance", None))
        self.relativeRadio.setText(_translate("matProp", "Relative Size:", None))
        self.label_2.setText(_translate("matProp", "Min", None))
        self.minSizeBox.setToolTip(_translate("matProp", "Sets minimum point size", None))
        self.label_3.setText(_translate("matProp", "Max", None))
        self.maxSizeBox.setToolTip(_translate("matProp", "Sets maximum point size", None))
        self.groupBox_8.setTitle(_translate("matProp", "Texture", None))
        self.textureList.setToolTip(_translate("matProp", "Associates a loaded texture with this material", None))
        self.groupBox_2.setTitle(_translate("matProp", "Fragment Program", None))
        self.fragList.setToolTip(_translate("matProp", "Associates a fragment program with this material", None))
        self.groupBox_3.setTitle(_translate("matProp", "Vertex Program", None))
        self.vertList.setToolTip(_translate("matProp", "Associates a vertex program with this material", None))
        self.geomBox.setTitle(_translate("matProp", "Geometry Program", None))

