# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/Measure2DView.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Measure2DView(object):
    def setupUi(self, Measure2DView):
        Measure2DView.setObjectName(_fromUtf8("Measure2DView"))
        Measure2DView.resize(642, 313)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Measure2DView)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.measureBox = QtGui.QGroupBox(Measure2DView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureBox.sizePolicy().hasHeightForWidth())
        self.measureBox.setSizePolicy(sizePolicy)
        self.measureBox.setObjectName(_fromUtf8("measureBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.measureBox)
        self.horizontalLayout_2.setContentsMargins(2, 7, 2, 2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.measureBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.objectList = QtGui.QListWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectList.sizePolicy().hasHeightForWidth())
        self.objectList.setSizePolicy(sizePolicy)
        self.objectList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.objectList.setObjectName(_fromUtf8("objectList"))
        self.horizontalLayout.addWidget(self.objectList)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.addContourButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addContourButton.sizePolicy().hasHeightForWidth())
        self.addContourButton.setSizePolicy(sizePolicy)
        self.addContourButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.addContourButton.setFlat(False)
        self.addContourButton.setObjectName(_fromUtf8("addContourButton"))
        self.horizontalLayout_3.addWidget(self.addContourButton)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.numCtrlBox = QtGui.QSpinBox(self.groupBox)
        self.numCtrlBox.setMaximum(64)
        self.numCtrlBox.setProperty("value", 4)
        self.numCtrlBox.setObjectName(_fromUtf8("numCtrlBox"))
        self.horizontalLayout_3.addWidget(self.numCtrlBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.addPointButton = QtGui.QPushButton(self.groupBox)
        self.addPointButton.setObjectName(_fromUtf8("addPointButton"))
        self.horizontalLayout_4.addWidget(self.addPointButton)
        self.addLineButton = QtGui.QPushButton(self.groupBox)
        self.addLineButton.setObjectName(_fromUtf8("addLineButton"))
        self.horizontalLayout_4.addWidget(self.addLineButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 6, 0, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.setStartButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setStartButton.sizePolicy().hasHeightForWidth())
        self.setStartButton.setSizePolicy(sizePolicy)
        self.setStartButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.setStartButton.setObjectName(_fromUtf8("setStartButton"))
        self.gridLayout.addWidget(self.setStartButton, 0, 1, 1, 1)
        self.cloneButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cloneButton.sizePolicy().hasHeightForWidth())
        self.cloneButton.setSizePolicy(sizePolicy)
        self.cloneButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.cloneButton.setObjectName(_fromUtf8("cloneButton"))
        self.gridLayout.addWidget(self.cloneButton, 2, 0, 1, 1)
        self.setPlaneButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setPlaneButton.sizePolicy().hasHeightForWidth())
        self.setPlaneButton.setSizePolicy(sizePolicy)
        self.setPlaneButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.setPlaneButton.setObjectName(_fromUtf8("setPlaneButton"))
        self.gridLayout.addWidget(self.setPlaneButton, 0, 0, 1, 1)
        self.delButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delButton.sizePolicy().hasHeightForWidth())
        self.delButton.setSizePolicy(sizePolicy)
        self.delButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.delButton.setObjectName(_fromUtf8("delButton"))
        self.gridLayout.addWidget(self.delButton, 2, 1, 1, 1)
        self.copyStepsButton = QtGui.QPushButton(self.groupBox)
        self.copyStepsButton.setObjectName(_fromUtf8("copyStepsButton"))
        self.gridLayout.addWidget(self.copyStepsButton, 1, 0, 1, 1)
        self.trackButton = QtGui.QPushButton(self.groupBox)
        self.trackButton.setObjectName(_fromUtf8("trackButton"))
        self.gridLayout.addWidget(self.trackButton, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.measureBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.show3DBox = QtGui.QCheckBox(self.groupBox_2)
        self.show3DBox.setObjectName(_fromUtf8("show3DBox"))
        self.verticalLayout_3.addWidget(self.show3DBox)
        self.saveButton = QtGui.QPushButton(self.groupBox_2)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.verticalLayout_3.addWidget(self.saveButton)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.trackGroup = QtGui.QGroupBox(self.measureBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackGroup.sizePolicy().hasHeightForWidth())
        self.trackGroup.setSizePolicy(sizePolicy)
        self.trackGroup.setObjectName(_fromUtf8("trackGroup"))
        self.formLayout = QtGui.QFormLayout(self.trackGroup)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.trackGroup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.trackSrcBox = QtGui.QComboBox(self.trackGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackSrcBox.sizePolicy().hasHeightForWidth())
        self.trackSrcBox.setSizePolicy(sizePolicy)
        self.trackSrcBox.setObjectName(_fromUtf8("trackSrcBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.trackSrcBox)
        self.label_2 = QtGui.QLabel(self.trackGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.trackDataBox = QtGui.QComboBox(self.trackGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackDataBox.sizePolicy().hasHeightForWidth())
        self.trackDataBox.setSizePolicy(sizePolicy)
        self.trackDataBox.setObjectName(_fromUtf8("trackDataBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.trackDataBox)
        self.verticalLayout_4.addWidget(self.trackGroup)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.measureBox)

        self.retranslateUi(Measure2DView)
        QtCore.QMetaObject.connectSlotsByName(Measure2DView)

    def retranslateUi(self, Measure2DView):
        Measure2DView.setWindowTitle(_translate("Measure2DView", "Form", None))
        self.measureBox.setTitle(_translate("Measure2DView", "Measurement", None))
        self.groupBox.setTitle(_translate("Measure2DView", "Elements", None))
        self.objectList.setToolTip(_translate("Measure2DView", "List of measurement objects", None))
        self.addContourButton.setToolTip(_translate("Measure2DView", "Add a contour (click and drag)", None))
        self.addContourButton.setText(_translate("Measure2DView", "Add Contour", None))
        self.label.setText(_translate("Measure2DView", "# Ctrls:", None))
        self.numCtrlBox.setToolTip(_translate("Measure2DView", "Set # of control points for the new contour", None))
        self.addPointButton.setToolTip(_translate("Measure2DView", "Add a point", None))
        self.addPointButton.setText(_translate("Measure2DView", "Add Point", None))
        self.addLineButton.setToolTip(_translate("Measure2DView", "Add a line (click and drag)", None))
        self.addLineButton.setText(_translate("Measure2DView", "Add Line", None))
        self.setStartButton.setToolTip(_translate("Measure2DView", "Set the selected object\'s start time to the current timestep (this will remove subsequent steps)", None))
        self.setStartButton.setText(_translate("Measure2DView", "Set Start Time", None))
        self.cloneButton.setToolTip(_translate("Measure2DView", "Clone the selected object onto the current plane", None))
        self.cloneButton.setText(_translate("Measure2DView", "Clone", None))
        self.setPlaneButton.setToolTip(_translate("Measure2DView", "Move the selected object to the current plane", None))
        self.setPlaneButton.setText(_translate("Measure2DView", "Set Plane", None))
        self.delButton.setToolTip(_translate("Measure2DView", "Delete the selected object", None))
        self.delButton.setText(_translate("Measure2DView", "Delete", None))
        self.copyStepsButton.setToolTip(_translate("Measure2DView", "Copy the first timestep to every step of the current source image", None))
        self.copyStepsButton.setText(_translate("Measure2DView", "Copy Steps", None))
        self.trackButton.setToolTip(_translate("Measure2DView", "Apply the selected motion tracking data to the first timestep of the selected object, replacing existing timesteps", None))
        self.trackButton.setText(_translate("Measure2DView", "Motion Track", None))
        self.groupBox_2.setTitle(_translate("Measure2DView", "Object", None))
        self.show3DBox.setToolTip(_translate("Measure2DView", "Show objects in 3D view", None))
        self.show3DBox.setText(_translate("Measure2DView", "Show in 3D", None))
        self.saveButton.setToolTip(_translate("Measure2DView", "Save measurement object to its file (eventually)", None))
        self.saveButton.setText(_translate("Measure2DView", "Save", None))
        self.trackGroup.setTitle(_translate("Measure2DView", "Tracking", None))
        self.label_3.setText(_translate("Measure2DView", "Source", None))
        self.trackSrcBox.setToolTip(_translate("Measure2DView", "Select the source image for the tracking data", None))
        self.label_2.setText(_translate("Measure2DView", "Data", None))
        self.trackDataBox.setToolTip(_translate("Measure2DView", "Select the directory with the tracking data", None))

import Resources_rc
