# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/ObjReprProp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ObjReprProp(object):
    def setupUi(self, ObjReprProp):
        ObjReprProp.setObjectName(_fromUtf8("ObjReprProp"))
        ObjReprProp.resize(285, 846)
        ObjReprProp.setStyleSheet(_fromUtf8(""))
        self.verticalLayout = QtGui.QVBoxLayout(ObjReprProp)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.propertiesBox = QtGui.QGroupBox(ObjReprProp)
        self.propertiesBox.setStyleSheet(_fromUtf8(""))
        self.propertiesBox.setObjectName(_fromUtf8("propertiesBox"))
        self.gridLayout = QtGui.QGridLayout(self.propertiesBox)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.propTable = QtGui.QTableWidget(self.propertiesBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propTable.sizePolicy().hasHeightForWidth())
        self.propTable.setSizePolicy(sizePolicy)
        self.propTable.setMinimumSize(QtCore.QSize(0, 170))
        self.propTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propTable.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.propTable.setAlternatingRowColors(True)
        self.propTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.propTable.setTextElideMode(QtCore.Qt.ElideNone)
        self.propTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.propTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.propTable.setShowGrid(False)
        self.propTable.setWordWrap(True)
        self.propTable.setObjectName(_fromUtf8("propTable"))
        self.propTable.setColumnCount(2)
        self.propTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.propTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.propTable.setHorizontalHeaderItem(1, item)
        self.propTable.horizontalHeader().setCascadingSectionResizes(True)
        self.propTable.horizontalHeader().setDefaultSectionSize(100)
        self.propTable.horizontalHeader().setStretchLastSection(False)
        self.propTable.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.propTable, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.propertiesBox)
        self.groupBox = QtGui.QGroupBox(ObjReprProp)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.propertyLayout = QtGui.QVBoxLayout(self.groupBox)
        self.propertyLayout.setContentsMargins(9, 1, 9, -1)
        self.propertyLayout.setObjectName(_fromUtf8("propertyLayout"))
        self.visibleCheckbox = QtGui.QCheckBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visibleCheckbox.sizePolicy().hasHeightForWidth())
        self.visibleCheckbox.setSizePolicy(sizePolicy)
        self.visibleCheckbox.setMinimumSize(QtCore.QSize(0, 0))
        self.visibleCheckbox.setObjectName(_fromUtf8("visibleCheckbox"))
        self.propertyLayout.addWidget(self.visibleCheckbox)
        self.handleCheckbox = QtGui.QCheckBox(self.groupBox)
        self.handleCheckbox.setObjectName(_fromUtf8("handleCheckbox"))
        self.propertyLayout.addWidget(self.handleCheckbox)
        self.bbCheckbox = QtGui.QCheckBox(self.groupBox)
        self.bbCheckbox.setObjectName(_fromUtf8("bbCheckbox"))
        self.propertyLayout.addWidget(self.bbCheckbox)
        self.verticalLayout.addWidget(self.groupBox)
        self.spectrumBox = QtGui.QGroupBox(ObjReprProp)
        self.spectrumBox.setEnabled(True)
        self.spectrumBox.setObjectName(_fromUtf8("spectrumBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.spectrumBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_11 = QtGui.QLabel(self.spectrumBox)
        self.label_11.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.specnameBox = QtGui.QComboBox(self.spectrumBox)
        self.specnameBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specnameBox.sizePolicy().hasHeightForWidth())
        self.specnameBox.setSizePolicy(sizePolicy)
        self.specnameBox.setObjectName(_fromUtf8("specnameBox"))
        self.horizontalLayout.addWidget(self.specnameBox)
        self.setSpecButton = QtGui.QPushButton(self.spectrumBox)
        self.setSpecButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setSpecButton.sizePolicy().hasHeightForWidth())
        self.setSpecButton.setSizePolicy(sizePolicy)
        self.setSpecButton.setObjectName(_fromUtf8("setSpecButton"))
        self.horizontalLayout.addWidget(self.setSpecButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.spectrumBox)
        self.materialBox = QtGui.QGroupBox(ObjReprProp)
        self.materialBox.setObjectName(_fromUtf8("materialBox"))
        self.formLayout = QtGui.QFormLayout(self.materialBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.matnameBox = QtGui.QComboBox(self.materialBox)
        self.matnameBox.setObjectName(_fromUtf8("matnameBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.matnameBox)
        self.applymatButton = QtGui.QPushButton(self.materialBox)
        self.applymatButton.setObjectName(_fromUtf8("applymatButton"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.applymatButton)
        self.label = QtGui.QLabel(self.materialBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addWidget(self.materialBox)
        self.groupBox1 = QtGui.QGroupBox(ObjReprProp)
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox1)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.transx = QtGui.QDoubleSpinBox(self.groupBox1)
        self.transx.setDecimals(6)
        self.transx.setMinimum(-100000.0)
        self.transx.setMaximum(100000.0)
        self.transx.setObjectName(_fromUtf8("transx"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.transx)
        self.label_2 = QtGui.QLabel(self.groupBox1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.transy = QtGui.QDoubleSpinBox(self.groupBox1)
        self.transy.setDecimals(6)
        self.transy.setMinimum(-100000.0)
        self.transy.setMaximum(100000.0)
        self.transy.setObjectName(_fromUtf8("transy"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.transy)
        self.transz = QtGui.QDoubleSpinBox(self.groupBox1)
        self.transz.setDecimals(6)
        self.transz.setMinimum(-100000.0)
        self.transz.setMaximum(100000.0)
        self.transz.setObjectName(_fromUtf8("transz"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.transz)
        self.scalex = QtGui.QDoubleSpinBox(self.groupBox1)
        self.scalex.setDecimals(6)
        self.scalex.setMinimum(-100000.0)
        self.scalex.setMaximum(100000.0)
        self.scalex.setSingleStep(0.1)
        self.scalex.setProperty("value", 1.0)
        self.scalex.setObjectName(_fromUtf8("scalex"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.scalex)
        self.scaley = QtGui.QDoubleSpinBox(self.groupBox1)
        self.scaley.setDecimals(6)
        self.scaley.setMinimum(-100000.0)
        self.scaley.setMaximum(100000.0)
        self.scaley.setSingleStep(0.1)
        self.scaley.setProperty("value", 1.0)
        self.scaley.setObjectName(_fromUtf8("scaley"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.scaley)
        self.scalez = QtGui.QDoubleSpinBox(self.groupBox1)
        self.scalez.setDecimals(6)
        self.scalez.setMinimum(-100000.0)
        self.scalez.setMaximum(100000.0)
        self.scalez.setSingleStep(0.1)
        self.scalez.setProperty("value", 1.0)
        self.scalez.setObjectName(_fromUtf8("scalez"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.scalez)
        self.yaw = QtGui.QDoubleSpinBox(self.groupBox1)
        self.yaw.setDecimals(6)
        self.yaw.setMinimum(-100000.0)
        self.yaw.setMaximum(100000.0)
        self.yaw.setSingleStep(0.314159)
        self.yaw.setObjectName(_fromUtf8("yaw"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.yaw)
        self.roll = QtGui.QDoubleSpinBox(self.groupBox1)
        self.roll.setDecimals(6)
        self.roll.setMinimum(-100000.0)
        self.roll.setMaximum(100000.0)
        self.roll.setSingleStep(0.314159)
        self.roll.setObjectName(_fromUtf8("roll"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.roll)
        self.pitch = QtGui.QDoubleSpinBox(self.groupBox1)
        self.pitch.setDecimals(6)
        self.pitch.setMinimum(-100000.0)
        self.pitch.setMaximum(100000.0)
        self.pitch.setSingleStep(0.314159)
        self.pitch.setObjectName(_fromUtf8("pitch"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.pitch)
        self.verticalLayout.addWidget(self.groupBox1)
        self.groupBox_2 = QtGui.QGroupBox(ObjReprProp)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.parentBox = QtGui.QComboBox(self.groupBox_2)
        self.parentBox.setObjectName(_fromUtf8("parentBox"))
        self.verticalLayout_2.addWidget(self.parentBox)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(ObjReprProp)
        QtCore.QMetaObject.connectSlotsByName(ObjReprProp)

    def retranslateUi(self, ObjReprProp):
        ObjReprProp.setWindowTitle(_translate("ObjReprProp", "Form", None))
        self.propertiesBox.setTitle(_translate("ObjReprProp", "Properties", None))
        item = self.propTable.horizontalHeaderItem(0)
        item.setText(_translate("ObjReprProp", "Name", None))
        item = self.propTable.horizontalHeaderItem(1)
        item.setText(_translate("ObjReprProp", "Value", None))
        self.visibleCheckbox.setToolTip(_translate("ObjReprProp", "Toggle representation visibility", None))
        self.visibleCheckbox.setText(_translate("ObjReprProp", "Visible", None))
        self.handleCheckbox.setToolTip(_translate("ObjReprProp", "Toggle handle visibility", None))
        self.handleCheckbox.setText(_translate("ObjReprProp", "Handle", None))
        self.bbCheckbox.setToolTip(_translate("ObjReprProp", "Toggle bound box visibility", None))
        self.bbCheckbox.setText(_translate("ObjReprProp", "Bounding Box", None))
        self.spectrumBox.setTitle(_translate("ObjReprProp", "Spectrum", None))
        self.label_11.setText(_translate("ObjReprProp", "Name", None))
        self.specnameBox.setToolTip(_translate("ObjReprProp", "Select spectrum", None))
        self.setSpecButton.setToolTip(_translate("ObjReprProp", "Set the selected spectrum to this object", None))
        self.setSpecButton.setText(_translate("ObjReprProp", "Set", None))
        self.materialBox.setTitle(_translate("ObjReprProp", "Material", None))
        self.matnameBox.setToolTip(_translate("ObjReprProp", "Select material name", None))
        self.applymatButton.setToolTip(_translate("ObjReprProp", "Apply material and recalculate data as needed", None))
        self.applymatButton.setText(_translate("ObjReprProp", "Apply", None))
        self.label.setText(_translate("ObjReprProp", "Name", None))
        self.groupBox1.setTitle(_translate("ObjReprProp", "Transform", None))
        self.transx.setToolTip(_translate("ObjReprProp", "X translation", None))
        self.label_2.setText(_translate("ObjReprProp", "Trans X:", None))
        self.label_3.setText(_translate("ObjReprProp", "Trans Y:", None))
        self.label_4.setText(_translate("ObjReprProp", "Trans Z:", None))
        self.label_5.setText(_translate("ObjReprProp", "Scale X:", None))
        self.label_6.setText(_translate("ObjReprProp", "Scale Y:", None))
        self.label_7.setText(_translate("ObjReprProp", "Scale Z:", None))
        self.label_8.setText(_translate("ObjReprProp", "Yaw:", None))
        self.label_9.setText(_translate("ObjReprProp", "Pitch:", None))
        self.label_10.setText(_translate("ObjReprProp", "Roll:", None))
        self.transy.setToolTip(_translate("ObjReprProp", "Y translation", None))
        self.transz.setToolTip(_translate("ObjReprProp", "Z translation", None))
        self.scalex.setToolTip(_translate("ObjReprProp", "X Scale", None))
        self.scaley.setToolTip(_translate("ObjReprProp", "Y scale", None))
        self.scalez.setToolTip(_translate("ObjReprProp", "Z scale", None))
        self.yaw.setToolTip(_translate("ObjReprProp", "Yaw in radians", None))
        self.roll.setToolTip(_translate("ObjReprProp", "Roll in radians", None))
        self.pitch.setToolTip(_translate("ObjReprProp", "Pitch in radians", None))
        self.groupBox_2.setTitle(_translate("ObjReprProp", "Parent Object", None))
        self.parentBox.setToolTip(_translate("ObjReprProp", "Select parent object to define this object\'s initial transform", None))

