# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/ScreenshotForm.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ScreenshotForm(object):
    def setupUi(self, ScreenshotForm):
        ScreenshotForm.setObjectName(_fromUtf8("ScreenshotForm"))
        ScreenshotForm.resize(504, 353)
        self.verticalLayout = QtGui.QVBoxLayout(ScreenshotForm)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalGroupBox = QtGui.QGroupBox(ScreenshotForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy)
        self.horizontalGroupBox.setObjectName(_fromUtf8("horizontalGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pathBox = QtGui.QLineEdit(self.horizontalGroupBox)
        self.pathBox.setObjectName(_fromUtf8("pathBox"))
        self.horizontalLayout.addWidget(self.pathBox)
        self.pathButton = QtGui.QPushButton(self.horizontalGroupBox)
        self.pathButton.setObjectName(_fromUtf8("pathButton"))
        self.horizontalLayout.addWidget(self.pathButton)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.groupBox_3 = QtGui.QGroupBox(ScreenshotForm)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.srcBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcBox.sizePolicy().hasHeightForWidth())
        self.srcBox.setSizePolicy(sizePolicy)
        self.srcBox.setObjectName(_fromUtf8("srcBox"))
        self.verticalLayout_4.addWidget(self.srcBox)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(ScreenshotForm)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.widthBox = QtGui.QSpinBox(self.groupBox_2)
        self.widthBox.setMinimum(1)
        self.widthBox.setMaximum(99999)
        self.widthBox.setProperty("value", 1)
        self.widthBox.setObjectName(_fromUtf8("widthBox"))
        self.horizontalLayout_3.addWidget(self.widthBox)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.heightBox = QtGui.QSpinBox(self.groupBox_2)
        self.heightBox.setMinimum(1)
        self.heightBox.setMaximum(99999)
        self.heightBox.setObjectName(_fromUtf8("heightBox"))
        self.horizontalLayout_3.addWidget(self.heightBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(ScreenshotForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.singleRadio = QtGui.QRadioButton(self.groupBox)
        self.singleRadio.setChecked(True)
        self.singleRadio.setObjectName(_fromUtf8("singleRadio"))
        self.verticalLayout_3.addWidget(self.singleRadio)
        self.multipleRadio = QtGui.QRadioButton(self.groupBox)
        self.multipleRadio.setObjectName(_fromUtf8("multipleRadio"))
        self.verticalLayout_3.addWidget(self.multipleRadio)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.startBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.startBox.setDecimals(3)
        self.startBox.setMaximum(9999.99)
        self.startBox.setObjectName(_fromUtf8("startBox"))
        self.horizontalLayout_2.addWidget(self.startBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.endBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.endBox.setDecimals(3)
        self.endBox.setMinimum(0.001)
        self.endBox.setMaximum(9999.99)
        self.endBox.setProperty("value", 1.0)
        self.endBox.setObjectName(_fromUtf8("endBox"))
        self.horizontalLayout_2.addWidget(self.endBox)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.fpsBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.fpsBox.setDecimals(3)
        self.fpsBox.setMinimum(0.001)
        self.fpsBox.setMaximum(9999.99)
        self.fpsBox.setProperty("value", 1.0)
        self.fpsBox.setObjectName(_fromUtf8("fpsBox"))
        self.horizontalLayout_2.addWidget(self.fpsBox)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.stepsBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.stepsBox.setDecimals(3)
        self.stepsBox.setMinimum(0.001)
        self.stepsBox.setMaximum(9999.99)
        self.stepsBox.setProperty("value", 1.0)
        self.stepsBox.setObjectName(_fromUtf8("stepsBox"))
        self.horizontalLayout_2.addWidget(self.stepsBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.totalLabel = QtGui.QLabel(self.groupBox)
        self.totalLabel.setObjectName(_fromUtf8("totalLabel"))
        self.horizontalLayout_4.addWidget(self.totalLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.saveButton = QtGui.QPushButton(ScreenshotForm)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_5.addWidget(self.saveButton)
        self.cancelButton = QtGui.QPushButton(ScreenshotForm)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_5.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(ScreenshotForm)
        QtCore.QMetaObject.connectSlotsByName(ScreenshotForm)
        ScreenshotForm.setTabOrder(self.saveButton, self.cancelButton)
        ScreenshotForm.setTabOrder(self.cancelButton, self.pathBox)
        ScreenshotForm.setTabOrder(self.pathBox, self.pathButton)
        ScreenshotForm.setTabOrder(self.pathButton, self.singleRadio)
        ScreenshotForm.setTabOrder(self.singleRadio, self.multipleRadio)
        ScreenshotForm.setTabOrder(self.multipleRadio, self.startBox)
        ScreenshotForm.setTabOrder(self.startBox, self.endBox)
        ScreenshotForm.setTabOrder(self.endBox, self.fpsBox)
        ScreenshotForm.setTabOrder(self.fpsBox, self.stepsBox)

    def retranslateUi(self, ScreenshotForm):
        ScreenshotForm.setWindowTitle(_translate("ScreenshotForm", "Save Screenshot(s)", None))
        self.horizontalGroupBox.setTitle(_translate("ScreenshotForm", "Path", None))
        self.pathButton.setText(_translate("ScreenshotForm", "&Choose...", None))
        self.groupBox_3.setTitle(_translate("ScreenshotForm", "Source", None))
        self.groupBox_2.setTitle(_translate("ScreenshotForm", "Resolution", None))
        self.label_5.setText(_translate("ScreenshotForm", "Width", None))
        self.label_6.setText(_translate("ScreenshotForm", "Height", None))
        self.groupBox.setTitle(_translate("ScreenshotForm", "Timestep(s)", None))
        self.singleRadio.setText(_translate("ScreenshotForm", "Single Timestep", None))
        self.multipleRadio.setText(_translate("ScreenshotForm", "Multiple Timesteps", None))
        self.label.setText(_translate("ScreenshotForm", "Start", None))
        self.label_2.setText(_translate("ScreenshotForm", "End", None))
        self.label_3.setText(_translate("ScreenshotForm", "Frames/s", None))
        self.label_4.setText(_translate("ScreenshotForm", "Steps/s", None))
        self.totalLabel.setText(_translate("ScreenshotForm", "Total # of Images: 1", None))
        self.saveButton.setText(_translate("ScreenshotForm", "&Save", None))
        self.cancelButton.setText(_translate("ScreenshotForm", "&Cancel", None))

