# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/Seg2DView.ui'
#
# Created: Mon Oct 17 15:55:12 2016
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Seg2DView(object):
    def setupUi(self, Seg2DView):
        Seg2DView.setObjectName(_fromUtf8("Seg2DView"))
        Seg2DView.resize(766, 277)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Seg2DView)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.segBox = QtGui.QGroupBox(Seg2DView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segBox.sizePolicy().hasHeightForWidth())
        self.segBox.setSizePolicy(sizePolicy)
        self.segBox.setObjectName(_fromUtf8("segBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.segBox)
        self.horizontalLayout_2.setContentsMargins(2, 7, 2, 2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.segBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.contourList = QtGui.QListWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contourList.sizePolicy().hasHeightForWidth())
        self.contourList.setSizePolicy(sizePolicy)
        self.contourList.setObjectName(_fromUtf8("contourList"))
        self.horizontalLayout.addWidget(self.contourList)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.addButton.setFlat(False)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.verticalLayout.addWidget(self.addButton)
        self.setPlaneButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setPlaneButton.sizePolicy().hasHeightForWidth())
        self.setPlaneButton.setSizePolicy(sizePolicy)
        self.setPlaneButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.setPlaneButton.setObjectName(_fromUtf8("setPlaneButton"))
        self.verticalLayout.addWidget(self.setPlaneButton)
        self.setTSButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setTSButton.sizePolicy().hasHeightForWidth())
        self.setTSButton.setSizePolicy(sizePolicy)
        self.setTSButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.setTSButton.setObjectName(_fromUtf8("setTSButton"))
        self.verticalLayout.addWidget(self.setTSButton)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.numCtrlBox = QtGui.QSpinBox(self.groupBox)
        self.numCtrlBox.setMaximum(64)
        self.numCtrlBox.setProperty("value", 4)
        self.numCtrlBox.setObjectName(_fromUtf8("numCtrlBox"))
        self.horizontalLayout_3.addWidget(self.numCtrlBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.cloneButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cloneButton.sizePolicy().hasHeightForWidth())
        self.cloneButton.setSizePolicy(sizePolicy)
        self.cloneButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.cloneButton.setObjectName(_fromUtf8("cloneButton"))
        self.verticalLayout.addWidget(self.cloneButton)
        self.delButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delButton.sizePolicy().hasHeightForWidth())
        self.delButton.setSizePolicy(sizePolicy)
        self.delButton.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.delButton.setObjectName(_fromUtf8("delButton"))
        self.verticalLayout.addWidget(self.delButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.segBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.showContoursBox = QtGui.QCheckBox(self.groupBox_2)
        self.showContoursBox.setObjectName(_fromUtf8("showContoursBox"))
        self.verticalLayout_3.addWidget(self.showContoursBox)
        self.genButton = QtGui.QPushButton(self.groupBox_2)
        self.genButton.setEnabled(False)
        self.genButton.setObjectName(_fromUtf8("genButton"))
        self.verticalLayout_3.addWidget(self.genButton)
        self.saveButton = QtGui.QPushButton(self.groupBox_2)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.verticalLayout_3.addWidget(self.saveButton)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.segBox)

        self.retranslateUi(Seg2DView)
        QtCore.QMetaObject.connectSlotsByName(Seg2DView)

    def retranslateUi(self, Seg2DView):
        Seg2DView.setWindowTitle(_translate("Seg2DView", "Form", None))
        self.segBox.setTitle(_translate("Seg2DView", "Segmentation", None))
        self.groupBox.setTitle(_translate("Seg2DView", "Contours", None))
        self.addButton.setToolTip(_translate("Seg2DView", "Add a contour on the current plane", None))
        self.addButton.setText(_translate("Seg2DView", "Add Contour", None))
        self.setPlaneButton.setToolTip(_translate("Seg2DView", "Move the selected contour to the current plane", None))
        self.setPlaneButton.setText(_translate("Seg2DView", "Set Plane", None))
        self.setTSButton.setToolTip(_translate("Seg2DView", "Set the selected contour\'s timestep to the current timestep", None))
        self.setTSButton.setText(_translate("Seg2DView", "Set Timestep", None))
        self.label.setText(_translate("Seg2DView", "# Ctrls:", None))
        self.numCtrlBox.setToolTip(_translate("Seg2DView", "Set # of control points for contours", None))
        self.cloneButton.setToolTip(_translate("Seg2DView", "Clone the selected contour onto the current plane", None))
        self.cloneButton.setText(_translate("Seg2DView", "Clone", None))
        self.delButton.setToolTip(_translate("Seg2DView", "Delete the selected contour", None))
        self.delButton.setText(_translate("Seg2DView", "Delete", None))
        self.groupBox_2.setTitle(_translate("Seg2DView", "Object", None))
        self.showContoursBox.setToolTip(_translate("Seg2DView", "Show segmentation contours in 3D view", None))
        self.showContoursBox.setText(_translate("Seg2DView", "Show Contours", None))
        self.genButton.setToolTip(_translate("Seg2DView", "Generate contours on image planes between existing contours", None))
        self.genButton.setText(_translate("Seg2DView", "Generate Contours", None))
        self.saveButton.setToolTip(_translate("Seg2DView", "Save segmentation to its file (eventually)", None))
        self.saveButton.setText(_translate("Seg2DView", "Save", None))

import Resources_rc
