# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/SegObjProp.ui'
#
# Created: Mon Oct 17 15:55:12 2016
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SegObjProp(object):
    def setupUi(self, SegObjProp):
        SegObjProp.setObjectName(_fromUtf8("SegObjProp"))
        SegObjProp.resize(335, 587)
        self.verticalLayout = QtGui.QVBoxLayout(SegObjProp)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(SegObjProp)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.propTable = QtGui.QTableWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propTable.sizePolicy().hasHeightForWidth())
        self.propTable.setSizePolicy(sizePolicy)
        self.propTable.setMinimumSize(QtCore.QSize(0, 120))
        self.propTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propTable.setAlternatingRowColors(True)
        self.propTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.propTable.setTextElideMode(QtCore.Qt.ElideNone)
        self.propTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.propTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.propTable.setShowGrid(False)
        self.propTable.setWordWrap(True)
        self.propTable.setObjectName(_fromUtf8("propTable"))
        self.propTable.setColumnCount(2)
        self.propTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.propTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.propTable.setHorizontalHeaderItem(1, item)
        self.propTable.horizontalHeader().setCascadingSectionResizes(True)
        self.propTable.horizontalHeader().setDefaultSectionSize(100)
        self.propTable.horizontalHeader().setStretchLastSection(False)
        self.propTable.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.propTable, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(SegObjProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.srcBox = QtGui.QComboBox(SegObjProp)
        self.srcBox.setObjectName(_fromUtf8("srcBox"))
        self.horizontalLayout.addWidget(self.srcBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.showButton = QtGui.QPushButton(SegObjProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showButton.sizePolicy().hasHeightForWidth())
        self.showButton.setSizePolicy(sizePolicy)
        self.showButton.setObjectName(_fromUtf8("showButton"))
        self.verticalLayout.addWidget(self.showButton)
        self.groupBox = QtGui.QGroupBox(SegObjProp)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.ahaBox = QtGui.QCheckBox(self.groupBox)
        self.ahaBox.setChecked(True)
        self.ahaBox.setObjectName(_fromUtf8("ahaBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ahaBox)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cavButton = QtGui.QRadioButton(self.groupBox)
        self.cavButton.setObjectName(_fromUtf8("cavButton"))
        self.gridLayout.addWidget(self.cavButton, 0, 1, 1, 1)
        self.hemButton = QtGui.QRadioButton(self.groupBox)
        self.hemButton.setChecked(True)
        self.hemButton.setObjectName(_fromUtf8("hemButton"))
        self.gridLayout.addWidget(self.hemButton, 0, 0, 1, 1)
        self.innerButton = QtGui.QRadioButton(self.groupBox)
        self.innerButton.setObjectName(_fromUtf8("innerButton"))
        self.gridLayout.addWidget(self.innerButton, 1, 1, 1, 1)
        self.outerButton = QtGui.QRadioButton(self.groupBox)
        self.outerButton.setObjectName(_fromUtf8("outerButton"))
        self.gridLayout.addWidget(self.outerButton, 1, 0, 1, 1)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.gridLayout)
        self.genMeshButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genMeshButton.sizePolicy().hasHeightForWidth())
        self.genMeshButton.setSizePolicy(sizePolicy)
        self.genMeshButton.setObjectName(_fromUtf8("genMeshButton"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.genMeshButton)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.refineBox = QtGui.QSpinBox(self.groupBox)
        self.refineBox.setMinimum(1)
        self.refineBox.setMaximum(6)
        self.refineBox.setObjectName(_fromUtf8("refineBox"))
        self.horizontalLayout_2.addWidget(self.refineBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.reinterpBox = QtGui.QSpinBox(self.groupBox)
        self.reinterpBox.setMinimum(0)
        self.reinterpBox.setMaximum(50)
        self.reinterpBox.setProperty("value", 20)
        self.reinterpBox.setObjectName(_fromUtf8("reinterpBox"))
        self.horizontalLayout_2.addWidget(self.reinterpBox)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(SegObjProp)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cavMaskButton = QtGui.QRadioButton(self.groupBox_3)
        self.cavMaskButton.setObjectName(_fromUtf8("cavMaskButton"))
        self.gridLayout_3.addWidget(self.cavMaskButton, 0, 1, 1, 1)
        self.hemMaskButton = QtGui.QRadioButton(self.groupBox_3)
        self.hemMaskButton.setObjectName(_fromUtf8("hemMaskButton"))
        self.gridLayout_3.addWidget(self.hemMaskButton, 0, 0, 1, 1)
        self.label2Button = QtGui.QRadioButton(self.groupBox_3)
        self.label2Button.setObjectName(_fromUtf8("label2Button"))
        self.gridLayout_3.addWidget(self.label2Button, 1, 1, 1, 1)
        self.hemcavButton = QtGui.QRadioButton(self.groupBox_3)
        self.hemcavButton.setObjectName(_fromUtf8("hemcavButton"))
        self.gridLayout_3.addWidget(self.hemcavButton, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.genMaskButton = QtGui.QPushButton(self.groupBox_3)
        self.genMaskButton.setObjectName(_fromUtf8("genMaskButton"))
        self.verticalLayout_2.addWidget(self.genMaskButton)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(SegObjProp)
        QtCore.QMetaObject.connectSlotsByName(SegObjProp)

    def retranslateUi(self, SegObjProp):
        SegObjProp.setWindowTitle(_translate("SegObjProp", "Form", None))
        self.groupBox_2.setTitle(_translate("SegObjProp", "Properties", None))
        item = self.propTable.horizontalHeaderItem(0)
        item.setText(_translate("SegObjProp", "Name", None))
        item = self.propTable.horizontalHeaderItem(1)
        item.setText(_translate("SegObjProp", "Value", None))
        self.label.setText(_translate("SegObjProp", "Source Image", None))
        self.showButton.setText(_translate("SegObjProp", "Show Segmentation View", None))
        self.groupBox.setTitle(_translate("SegObjProp", "Generate Mesh", None))
        self.ahaBox.setText(_translate("SegObjProp", "Include AHA Field", None))
        self.cavButton.setText(_translate("SegObjProp", "Cavity Mesh", None))
        self.hemButton.setText(_translate("SegObjProp", "Hemisphere Mesh", None))
        self.innerButton.setText(_translate("SegObjProp", "Inner Surface", None))
        self.outerButton.setText(_translate("SegObjProp", "Outer Surface", None))
        self.genMeshButton.setText(_translate("SegObjProp", "Generate", None))
        self.label_2.setText(_translate("SegObjProp", "Refine", None))
        self.label_3.setText(_translate("SegObjProp", "Reinterpolate", None))
        self.groupBox_3.setTitle(_translate("SegObjProp", "Generate Mask", None))
        self.cavMaskButton.setText(_translate("SegObjProp", "Cavity Mask", None))
        self.hemMaskButton.setText(_translate("SegObjProp", "Hemisphere Mask", None))
        self.label2Button.setText(_translate("SegObjProp", "2 Label Mask", None))
        self.hemcavButton.setText(_translate("SegObjProp", "Hemi+Cavity Mask", None))
        self.genMaskButton.setText(_translate("SegObjProp", "Generate", None))

