# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/SliceObjProp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SliceObjProp(object):
    def setupUi(self, SliceObjProp):
        SliceObjProp.setObjectName(_fromUtf8("SliceObjProp"))
        SliceObjProp.resize(455, 601)
        self.verticalLayout = QtGui.QVBoxLayout(SliceObjProp)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(SliceObjProp)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.propTable = QtGui.QTableWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propTable.sizePolicy().hasHeightForWidth())
        self.propTable.setSizePolicy(sizePolicy)
        self.propTable.setMinimumSize(QtCore.QSize(0, 120))
        self.propTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.propTable.setAlternatingRowColors(True)
        self.propTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.propTable.setTextElideMode(QtCore.Qt.ElideNone)
        self.propTable.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.propTable.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.propTable.setShowGrid(False)
        self.propTable.setWordWrap(True)
        self.propTable.setObjectName(_fromUtf8("propTable"))
        self.propTable.setColumnCount(2)
        self.propTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.propTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.propTable.setHorizontalHeaderItem(1, item)
        self.propTable.horizontalHeader().setCascadingSectionResizes(True)
        self.propTable.horizontalHeader().setDefaultSectionSize(100)
        self.propTable.horizontalHeader().setStretchLastSection(False)
        self.propTable.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.propTable, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(SliceObjProp)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.selTable = QtGui.QTableWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selTable.sizePolicy().hasHeightForWidth())
        self.selTable.setSizePolicy(sizePolicy)
        self.selTable.setMinimumSize(QtCore.QSize(0, 120))
        self.selTable.setProperty("showDropIndicator", False)
        self.selTable.setDragDropOverwriteMode(False)
        self.selTable.setAlternatingRowColors(False)
        self.selTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.selTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.selTable.setShowGrid(False)
        self.selTable.setObjectName(_fromUtf8("selTable"))
        self.selTable.setColumnCount(2)
        self.selTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.selTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.selTable.setHorizontalHeaderItem(1, item)
        self.selTable.horizontalHeader().setVisible(True)
        self.selTable.horizontalHeader().setCascadingSectionResizes(True)
        self.selTable.verticalHeader().setVisible(False)
        self.selTable.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_2.addWidget(self.selTable)
        self.verticalLayout.addWidget(self.groupBox)
        self.updateButton = QtGui.QPushButton(SliceObjProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateButton.sizePolicy().hasHeightForWidth())
        self.updateButton.setSizePolicy(sizePolicy)
        self.updateButton.setObjectName(_fromUtf8("updateButton"))
        self.verticalLayout.addWidget(self.updateButton)
        self.createReprBox = QtGui.QGroupBox(SliceObjProp)
        self.createReprBox.setAutoFillBackground(False)
        self.createReprBox.setFlat(False)
        self.createReprBox.setCheckable(False)
        self.createReprBox.setObjectName(_fromUtf8("createReprBox"))
        self.formLayout = QtGui.QFormLayout(self.createReprBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.createReprBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.reprsBox = QtGui.QComboBox(self.createReprBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reprsBox.sizePolicy().hasHeightForWidth())
        self.reprsBox.setSizePolicy(sizePolicy)
        self.reprsBox.setObjectName(_fromUtf8("reprsBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.reprsBox)
        self.createButton = QtGui.QPushButton(self.createReprBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createButton.sizePolicy().hasHeightForWidth())
        self.createButton.setSizePolicy(sizePolicy)
        self.createButton.setObjectName(_fromUtf8("createButton"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.createButton)
        self.verticalLayout.addWidget(self.createReprBox)
        self.groupBox_4 = QtGui.QGroupBox(SliceObjProp)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.modeBox = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeBox.sizePolicy().hasHeightForWidth())
        self.modeBox.setSizePolicy(sizePolicy)
        self.modeBox.setObjectName(_fromUtf8("modeBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.modeBox)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(SliceObjProp)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.alignObjBox = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignObjBox.sizePolicy().hasHeightForWidth())
        self.alignObjBox.setSizePolicy(sizePolicy)
        self.alignObjBox.setObjectName(_fromUtf8("alignObjBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.alignObjBox)
        self.alignObjButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignObjButton.sizePolicy().hasHeightForWidth())
        self.alignObjButton.setSizePolicy(sizePolicy)
        self.alignObjButton.setObjectName(_fromUtf8("alignObjButton"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.alignObjButton)
        self.reverseBox = QtGui.QCheckBox(self.groupBox_3)
        self.reverseBox.setObjectName(_fromUtf8("reverseBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.reverseBox)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(SliceObjProp)
        QtCore.QMetaObject.connectSlotsByName(SliceObjProp)

    def retranslateUi(self, SliceObjProp):
        SliceObjProp.setWindowTitle(_translate("SliceObjProp", "Form", None))
        self.groupBox_2.setTitle(_translate("SliceObjProp", "Properties", None))
        item = self.propTable.horizontalHeaderItem(0)
        item.setText(_translate("SliceObjProp", "Name", None))
        item = self.propTable.horizontalHeaderItem(1)
        item.setText(_translate("SliceObjProp", "Value", None))
        self.groupBox.setTitle(_translate("SliceObjProp", "Selected Representations", None))
        item = self.selTable.horizontalHeaderItem(0)
        item.setText(_translate("SliceObjProp", "Sel", None))
        item = self.selTable.horizontalHeaderItem(1)
        item.setText(_translate("SliceObjProp", "Representation", None))
        self.updateButton.setText(_translate("SliceObjProp", "Update", None))
        self.createReprBox.setTitle(_translate("SliceObjProp", "Create Representation", None))
        self.label.setText(_translate("SliceObjProp", "Type", None))
        self.createButton.setText(_translate("SliceObjProp", "Create", None))
        self.groupBox_4.setTitle(_translate("SliceObjProp", "Settings", None))
        self.label_3.setText(_translate("SliceObjProp", "Mode", None))
        self.groupBox_3.setTitle(_translate("SliceObjProp", "Align to Object", None))
        self.label_2.setText(_translate("SliceObjProp", "Name", None))
        self.alignObjButton.setText(_translate("SliceObjProp", "Set Alignment", None))
        self.reverseBox.setText(_translate("SliceObjProp", "Reversed", None))

